const MAIHAR=new Set(['AMARPATAN','MAIHAR','RAMNAGAR']);const SATNA=new Set(['MAJHGAWAN','NAGOD','RAMPUR BAGHELAN','SOHAWAL','SATNA','UNCHAHARA']);
const BOOT_REPORT=window.AUTO_REPORT||window.SAMPLE_REPORT||{};
let rows=BOOT_REPORT.rows||[],official=BOOT_REPORT.official||[],workmix=BOOT_REPORT.workmix||[],reportTitle=BOOT_REPORT.title||'',pendingFile=null,view='official',lastExport=[];
let autoMeta=BOOT_REPORT.meta||{mode:(window.AUTO_REPORT?'auto':'sample'),updatedAt:null,source:null,status:(window.AUTO_REPORT?'ok':'sample')};
const $=id=>document.getElementById(id),num=x=>Number(x)||0,clean=x=>String(x??'').trim(),fmt=n=>new Intl.NumberFormat('en-IN').format(Math.round(num(n))),pct=(a,b)=>b?(num(a)*100/num(b)):0,esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function districtOf(j){j=clean(j).toUpperCase();return MAIHAR.has(j)?'MAIHAR':SATNA.has(j)?'SATNA':'OTHER'}function extractDate(t){const m=String(t).match(/(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})/);return m?`${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')}-${m[3]}`:'—'}
function updateAutoStatus(){const el=$('autoStatus');if(!el)return;const mode=autoMeta?.mode||'sample';const when=autoMeta?.updatedAt?new Date(autoMeta.updatedAt).toLocaleString('hi-IN'):'—';const source=autoMeta?.source||'Bundled sample data';const ok=autoMeta?.status==='ok';el.innerHTML=`<span class="status-pill ${ok?'ok':'sample'}">${ok?'AUTO DATA':'SAMPLE / MANUAL'}</span><b>${ok?'Last auto update':'Current mode'}:</b> ${ok?esc(when):esc(mode)} <span class="status-source">${esc(source)}</span>`;}
function sum(a,k){return a.reduce((s,r)=>s+num(r[k]),0)}function filterRows(a){const d=$('districtFilter').value,j=$('janpadFilter').value,e=$('engineerFilter').value,c=$('clusterFilter').value;return a.filter(r=>(d==='ALL'||districtOf(r.janpad)===d)&&(j==='ALL'||r.janpad===j)&&(e==='ALL'||!r.engineer||r.engineer===e)&&(c==='ALL'||!r.cluster||r.cluster===c))}
function optionize(el,values,label){const cur=el.value;el.innerHTML=`<option value="ALL">${label}</option>`+[...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'hi')).map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if([...el.options].some(o=>o.value===cur))el.value=cur}
function refreshFilters(){let b=rows;if($('districtFilter').value!=='ALL')b=b.filter(r=>districtOf(r.janpad)===$('districtFilter').value);optionize($('janpadFilter'),b.map(r=>r.janpad),'सभी Janpad');if($('janpadFilter').value!=='ALL')b=b.filter(r=>r.janpad===$('janpadFilter').value);optionize($('engineerFilter'),b.map(r=>r.engineer),'सभी Engineer');if($('engineerFilter').value!=='ALL')b=b.filter(r=>r.engineer===$('engineerFilter').value);optionize($('clusterFilter'),b.map(r=>r.cluster),'सभी Cluster')}
function filteredRows(){return filterRows(rows)}
function kpis(list){const gps=sum(list,'gps'),prog=sum(list,'gpsProgress'),ongoing=sum(list,'ongoing'),mr=sum(list,'worksMR'),labour=sum(list,'labour'),mrs=sum(list,'mrs');$('kpis').innerHTML=[['Gram Panchayats',gps,'Total GP'],['GPs with Progress',prog,`${pct(prog,gps).toFixed(1)}% coverage`],['Ongoing Works',ongoing,'Work load'],['Works with MR',mr,`${pct(mr,ongoing).toFixed(1)}% of ongoing`],['Labour Engagement',labour,'e-Muster based'],['Muster Rolls',mrs,'MR count']].map(x=>`<div class="kpi"><small>${x[0]}</small><strong>${fmt(x[1])}</strong><em>${x[2]}</em></div>`).join('')}
function aggregate(a,keys,metrics){const m=new Map();for(const r of a){const id=keys.map(k=>clean(r[k])).join('¦');if(!m.has(id)){const z={};keys.forEach(k=>z[k]=clean(r[k]));metrics.forEach(k=>z[k]=0);m.set(id,z)}const z=m.get(id);metrics.forEach(k=>z[k]+=num(r[k]))}return [...m.values()]}
function mixMap(){const m=new Map();for(const r of workmix){const k=[r.janpad,r.engineer,r.cluster,r.panchayat].map(clean).join('¦');m.set(k,r)}return m}
function engineerData(list){const mm=mixMap();const enriched=list.map(r=>{const x=mm.get([r.janpad,r.engineer,r.cluster,r.panchayat].map(clean).join('¦'))||{};return {...r,pmayOngoing:num(x.pmayOngoing),ekOngoing:num(x.ekOngoing),currentFYActive:num(x.currentFYActive)}});return aggregate(enriched,['janpad','engineer','cluster'],['gps','gpsProgress','ongoing','worksMR','labour','mrs','noEkyc','pmayOngoing','ekOngoing','currentFYActive'])}
function officialFiltered(){let a=official;if($('districtFilter').value!=='ALL')a=a.filter(r=>districtOf(r.janpad)===$('districtFilter').value);if($('janpadFilter').value!=='ALL')a=a.filter(r=>r.janpad===$('janpadFilter').value);return a}
function cell(v,isnum=false){return `<td>${isnum?fmt(v):esc(v)}</td>`}function badge(a,b){const p=pct(a,b);return `<span class="badge ${p>=10?'good':'warn'}">${p.toFixed(1)}%</span>`}
function renderOfficial(){const data=officialFiltered();lastExport=data;$('viewTitle').textContent='Official Janpad Daily Report';$('viewMeta').textContent=`${data.length} Janpad • ${extractDate(reportTitle)}`;let h=`<thead><tr><th rowspan="2">District</th><th rowspan="2">Janpad</th><th colspan="3">Gram Panchayat</th><th colspan="4">All Types of Works</th><th colspan="2">Individual Land (Cat-IV)</th><th colspan="3">Community Works</th><th colspan="3">PMAY-G</th><th colspan="4">Ek Bagiya</th></tr><tr><th>Total GP</th><th>Muster GP</th><th>Dysfunctional</th><th>Labour</th><th>Works with MR</th><th>Ongoing</th><th>MR %</th><th>Labour</th><th>Works MR</th><th>Labour</th><th>Works MR</th><th>Share %</th><th>Ongoing</th><th>MR Issued</th><th>MR %</th><th>Labour</th><th>Ongoing</th><th>MR Issued</th><th>MR %</th></tr></thead><tbody>`;for(const r of data){h+=`<tr>${cell(districtOf(r.janpad))}${cell(r.janpad)}${cell(r.totalGP,true)}${cell(r.musterGP,true)}${cell(r.dysfunctionalGP,true)}${cell(r.labourAll,true)}${cell(r.mrAll,true)}${cell(r.ongoingAll,true)}<td>${badge(r.mrAll,r.ongoingAll)}</td>${cell(r.labourIndividual,true)}${cell(r.mrIndividual,true)}${cell(r.labourCommunity,true)}${cell(r.mrCommunity,true)}<td>${badge(r.mrCommunity,r.mrAll)}</td>${cell(r.pmayOngoing,true)}${cell(r.pmayMR,true)}<td>${badge(r.pmayMR,r.pmayOngoing)}</td>${cell(r.ekLabour,true)}${cell(r.ekOngoing,true)}${cell(r.ekMR,true)}<td>${badge(r.ekMR,r.ekOngoing)}</td></tr>`}const keys=['totalGP','musterGP','dysfunctionalGP','labourAll','mrAll','ongoingAll','labourIndividual','mrIndividual','labourCommunity','mrCommunity','pmayOngoing','pmayMR','ekLabour','ekOngoing','ekMR'],t={};keys.forEach(k=>t[k]=sum(data,k));h+=`<tr class="total-row"><td>TOTAL</td><td></td>${cell(t.totalGP,true)}${cell(t.musterGP,true)}${cell(t.dysfunctionalGP,true)}${cell(t.labourAll,true)}${cell(t.mrAll,true)}${cell(t.ongoingAll,true)}<td>${pct(t.mrAll,t.ongoingAll).toFixed(1)}%</td>${cell(t.labourIndividual,true)}${cell(t.mrIndividual,true)}${cell(t.labourCommunity,true)}${cell(t.mrCommunity,true)}<td>${pct(t.mrCommunity,t.mrAll).toFixed(1)}%</td>${cell(t.pmayOngoing,true)}${cell(t.pmayMR,true)}<td>${pct(t.pmayMR,t.pmayOngoing).toFixed(1)}%</td>${cell(t.ekLabour,true)}${cell(t.ekOngoing,true)}${cell(t.ekMR,true)}<td>${pct(t.ekMR,t.ekOngoing).toFixed(1)}%</td></tr></tbody>`;$('reportTable').innerHTML=h}
function standardTable(data,cols,title){lastExport=data;$('viewTitle').textContent=title;$('viewMeta').textContent=`${fmt(data.length)} rows • ${extractDate(reportTitle)}`;const nums=new Set(cols.filter(x=>x[2]).map(x=>x[0]));let h='<thead><tr>'+cols.map(c=>`<th>${c[1]}</th>`).join('')+'<th>MR Coverage</th></tr></thead><tbody>';for(const r of data){h+='<tr>'+cols.map(c=>cell(r[c[0]],nums.has(c[0]))).join('')+`<td>${badge(r.worksMR,r.ongoing)}</td></tr>`}const total={};nums.forEach(k=>total[k]=sum(data,k));h+=`<tr class="total-row">${cols.map((c,i)=>`<td>${i===0?'TOTAL':nums.has(c[0])?fmt(total[c[0]]):''}</td>`).join('')}<td>${pct(total.worksMR,total.ongoing).toFixed(1)}%</td></tr></tbody>`;$('reportTable').innerHTML=h}
function render(){const list=filteredRows();$('reportDate').textContent=extractDate(reportTitle);kpis(list);$('reportTable').className='report-table '+(view==='official'?'official-grid':view==='engineer'?'engineer-grid':view==='district'?'district-grid':'gp-grid');if(view==='official')return renderOfficial();if(view==='engineer'){const d=engineerData(list);return standardTable(d,[['janpad','Janpad'],['engineer','Engineer / Upyantri'],['cluster','Cluster'],['gps','GP',1],['gpsProgress','GP Progress',1],['labour','Labour',1],['ongoing','Ongoing Works',1],['worksMR','Works with MR',1],['mrs','Muster Rolls',1],['pmayOngoing','PMAY-G Ongoing',1],['ekOngoing','Ek Bagiya Ongoing',1],['currentFYActive','Current FY Active Works',1]],'Engineer-wise Daily Report')}if(view==='district'){const d=aggregate(list.map(r=>({...r,district:districtOf(r.janpad)})),['district'],['gps','gpsProgress','ongoing','worksMR','labour','mrs','noEkyc']);return standardTable(d,[['district','District'],['gps','Total GP',1],['gpsProgress','GP Progress',1],['labour','Labour',1],['ongoing','Ongoing Works',1],['worksMR','Works with MR',1],['mrs','Muster Rolls',1]],'Full District Report')}return standardTable(list,[['janpad','Janpad'],['engineer','Engineer'],['cluster','Cluster'],['panchayat','Gram Panchayat'],['labour','Labour',1],['ongoing','Ongoing Works',1],['worksMR','Works with MR',1],['mrs','Muster Rolls',1]],'Gram Panchayat Detail')}
function sheetArray(wb,name){const s=wb.Sheets[name];return s?XLSX.utils.sheet_to_json(s,{header:1,defval:''}):[]}
function parseWorkbook(wb){const a=sheetArray(wb,'RepDay');if(!a.length)throw new Error('RepDay sheet नहीं मिली।');reportTitle=clean(a?.[0]?.[0]);rows=[];for(let i=3;i<a.length;i++){const r=a[i];if(!clean(r[0])||!clean(r[1])||!clean(r[5]))continue;rows.push({janpad:clean(r[0]).toUpperCase(),engineer:clean(r[1]),cluster:clean(r[2]),ongoing:num(r[3]),panchayat:clean(r[5]).toUpperCase(),gps:num(r[6]),gpsProgress:num(r[7]),labour:num(r[8]),worksMR:num(r[9]),noEkyc:num(r[10]),mrs:num(r[11])})}
 const s1=sheetArray(wb,'Sheet1');official=[];for(const ix of [3,4,5,7,8,9,10,11]){const r=s1[ix]||[];if(!clean(r[1]))continue;official.push({janpad:clean(r[1]).toUpperCase(),totalGP:num(r[2]),musterGP:num(r[3]),dysfunctionalGP:num(r[4]),labourAll:num(r[5]),mrAll:num(r[6]),ongoingAll:num(r[7]),labourIndividual:num(r[9]),mrIndividual:num(r[10]),labourCommunity:num(r[11]),mrCommunity:num(r[12]),pmayOngoing:num(r[14]),pmayMR:num(r[15]),ekLabour:num(r[17]),ekOngoing:num(r[18]),ekMR:num(r[19])})}
 const gpmap=new Map(rows.map(r=>[[r.janpad,r.panchayat].join('¦'),[r.engineer,r.cluster]]));workmix=[];const wm=new Map(),v=sheetArray(wb,'VBG');for(let i=4;i<v.length;i++){const r=v[i],jan=clean(r[2]).toUpperCase(),gp=clean(r[3]).toUpperCase(),fy=clean(r[4]),status=clean(r[5]).toLowerCase(),code=clean(r[6]),name=clean(r[7]),wt=clean(r[8]);if(!jan||!gp||!code||!status.includes('ongoing'))continue;const ec=gpmap.get([jan,gp].join('¦'))||['Unmapped','Unmapped'],key=[jan,ec[0],ec[1],gp].join('¦');if(!wm.has(key))wm.set(key,{janpad:jan,engineer:ec[0],cluster:ec[1],panchayat:gp,workTotal:0,pmayOngoing:0,ekOngoing:0,currentFYActive:0});const z=wm.get(key);z.workTotal++;if(wt.toLowerCase().includes('pmay'))z.pmayOngoing++;if(wt.toLowerCase()==='ek bagiya'&&['2025-2026','2026-2027'].includes(fy)&&!/(school|prathmik|madhyamik|shala|vidyalaya|प्राथमिक|माध्यमिक|शाला|विद्यालय)/i.test(name))z.ekOngoing++;if(num(r[21])>0)z.currentFYActive++}workmix=[...wm.values()];if(!rows.length)throw new Error('RepDay में usable data नहीं मिला।')}
$('fileInput').addEventListener('change',e=>{pendingFile=e.target.files[0]||null;$('fileStatus').textContent=pendingFile?`Selected: ${pendingFile.name}`:'कोई file नहीं चुनी गई'});$('generateBtn').addEventListener('click',async()=>{if(!pendingFile){render();return}try{if(typeof XLSX==='undefined')throw new Error('Excel reader load नहीं हुआ।');$('fileStatus').textContent='Excel पढ़ी जा रही है…';const buf=await pendingFile.arrayBuffer();parseWorkbook(XLSX.read(buf,{type:'array'}));autoMeta={mode:'manual',updatedAt:new Date().toISOString(),source:pendingFile.name,status:'manual'};refreshFilters();render();updateAutoStatus();updateAutoStatus();$('fileStatus').textContent=`Generated: ${pendingFile.name} • ${fmt(rows.length)} GP rows`}catch(e){$('fileStatus').textContent='Error: '+e.message;alert(e.message)}});
['districtFilter','janpadFilter','engineerFilter','clusterFilter'].forEach(id=>$(id).addEventListener('change',()=>{refreshFilters();render()}));$('resetBtn').addEventListener('click',()=>{$('districtFilter').value='ALL';refreshFilters();$('janpadFilter').value=$('engineerFilter').value=$('clusterFilter').value='ALL';render()});$('printBtn').addEventListener('click',()=>window.print());document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');view=b.dataset.view;render()}));
$('csvBtn').addEventListener('click',()=>{if(!lastExport.length)return;const keys=Object.keys(lastExport[0]);const q=v=>'"'+String(v??'').replaceAll('"','""')+'"';const csv='\ufeff'+[keys.join(','),...lastExport.map(r=>keys.map(k=>q(r[k])).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`daily-report-${view}-${extractDate(reportTitle)}.csv`;a.click();URL.revokeObjectURL(a.href)});refreshFilters();render();
// V6: Font size and Portrait/Landscape print controls
(function(){
  let fontScale=1;
  const root=document.documentElement;
  const minus=document.getElementById('fontMinusBtn');
  const plus=document.getElementById('fontPlusBtn');
  const orient=document.getElementById('printOrientation');
  const printBtn=document.getElementById('printBtn');
  function applyScale(){root.style.setProperty('--table-font-scale',fontScale.toFixed(2));}
  minus?.addEventListener('click',()=>{fontScale=Math.max(.75,+(fontScale-.10).toFixed(2));applyScale();});
  plus?.addEventListener('click',()=>{fontScale=Math.min(1.60,+(fontScale+.10).toFixed(2));applyScale();});
  function setPrintOrientation(){
    const mode=orient?.value==='portrait'?'portrait':'landscape';
    document.body.classList.toggle('print-portrait',mode==='portrait');
    document.body.classList.toggle('print-landscape',mode==='landscape');
    let st=document.getElementById('dynamicPrintPageStyle');
    if(!st){st=document.createElement('style');st.id='dynamicPrintPageStyle';document.head.appendChild(st);}
    st.textContent=`@media print{@page{size:A4 ${mode};margin:7mm}}`;
  }
  orient?.addEventListener('change',setPrintOrientation);
  if(printBtn){
    const cloned=printBtn.cloneNode(true);
    printBtn.parentNode.replaceChild(cloned,printBtn);
    cloned.addEventListener('click',()=>{setPrintOrientation();setTimeout(()=>window.print(),30);});
  }
  setPrintOrientation();applyScale();
})();
