const MAIHAR=new Set(['AMARPATAN','MAIHAR','RAMNAGAR']);const SATNA=new Set(['MAJHGAWAN','NAGOD','RAMPUR BAGHELAN','SOHAWAL','SATNA','UNCHAHARA']);
const BOOT_REPORT=window.AUTO_REPORT||window.SAMPLE_REPORT||{};
let rows=BOOT_REPORT.rows||[],official=BOOT_REPORT.official||[],daily=BOOT_REPORT.daily||[],workmix=BOOT_REPORT.workmix||[],categorymix=BOOT_REPORT.categorymix||[],reportTitle=BOOT_REPORT.title||'',pendingFile=null,view='official',lastExport=[];
let autoMeta=BOOT_REPORT.meta||{mode:(window.AUTO_REPORT?'auto':'sample'),updatedAt:null,source:null,status:(window.AUTO_REPORT?'ok':'sample')};
const $=id=>document.getElementById(id),num=x=>Number(x)||0,clean=x=>String(x??'').trim(),fmt=n=>new Intl.NumberFormat('en-IN').format(Math.round(num(n))),pct=(a,b)=>b?(num(a)*100/num(b)):0,esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const normJanpad=v=>{const j=clean(v).toUpperCase();return j==='SOHAWAL'?'SATNA':j};
function districtOf(j){j=clean(j).toUpperCase();return MAIHAR.has(j)?'MAIHAR':SATNA.has(j)?'SATNA':'OTHER'}function extractDate(t){const m=String(t).match(/(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})/);return m?`${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')}-${m[3]}`:'—'}function todayDate(){const d=new Date();return `${String(d.getDate()).padStart(2,'0')}-${String(d.getMonth()+1).padStart(2,'0')}-${d.getFullYear()}`}
function updateAutoStatus(){const el=$('autoStatus');if(!el)return;const mode=autoMeta?.mode||'sample';const when=autoMeta?.updatedAt?new Date(autoMeta.updatedAt).toLocaleString('hi-IN'):'—';const source=autoMeta?.source||'Bundled sample data';const ok=autoMeta?.status==='ok';const sd=autoMeta?.sourceDates||{};const ds=[sd.Sheet1?`Sheet1: ${sd.Sheet1}`:'',sd.RepDay?`RepDay: ${sd.RepDay}`:''].filter(Boolean).join(' • ');el.innerHTML=`<span class="status-pill ${ok?'ok':'sample'}">${ok?'AUTO DATA':'SAMPLE / MANUAL'}</span><b>${ok?'Last auto update':'Current mode'}:</b> ${ok?esc(when):esc(mode)} <span class="status-source">${esc(source)}</span>${ds?` <span class="status-source">| Data date: ${esc(ds)}</span>`:''}`;}
function sum(a,k){return a.reduce((s,r)=>s+num(r[k]),0)}function filterRows(a){const d=$('districtFilter').value,j=$('janpadFilter').value,e=$('engineerFilter').value,c=$('clusterFilter').value;return a.filter(r=>(d==='ALL'||districtOf(r.janpad)===d)&&(j==='ALL'||r.janpad===j)&&(e==='ALL'||!r.engineer||r.engineer===e)&&(c==='ALL'||!r.cluster||r.cluster===c))}
function optionize(el,values,label){const cur=el.value;el.innerHTML=`<option value="ALL">${label}</option>`+[...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'hi')).map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if([...el.options].some(o=>o.value===cur))el.value=cur}
function refreshFilters(){let b=rows;if($('districtFilter').value!=='ALL')b=b.filter(r=>districtOf(r.janpad)===$('districtFilter').value);optionize($('janpadFilter'),b.map(r=>r.janpad),'सभी Janpad');if($('janpadFilter').value!=='ALL')b=b.filter(r=>r.janpad===$('janpadFilter').value);optionize($('engineerFilter'),b.map(r=>r.engineer),'सभी Engineer');if($('engineerFilter').value!=='ALL')b=b.filter(r=>r.engineer===$('engineerFilter').value);optionize($('clusterFilter'),b.map(r=>r.cluster),'सभी Cluster')}
function filteredRows(){return filterRows(rows)}
function dailyFiltered(){let a=daily;if($('districtFilter').value!=='ALL')a=a.filter(r=>districtOf(r.janpad)===$('districtFilter').value);if($('janpadFilter').value!=='ALL')a=a.filter(r=>r.janpad===$('janpadFilter').value);return a}
function kpis(list){const broadFilters=$('engineerFilter').value==='ALL'&&$('clusterFilter').value==='ALL';if(broadFilters&&daily.length){const dd=dailyFiltered(),oo=officialFiltered(),gps=sum(dd,'totalGP'),prog=sum(dd,'gpsProgress'),mr=sum(dd,'worksMR'),labour=sum(dd,'labour'),mrs=sum(dd,'mrs'),ongoing=sum(oo,'ongoingAll');$('kpis').innerHTML=[['Gram Panchayats',gps,'Total GP'],['GPs with Progress',prog,`${pct(prog,gps).toFixed(1)}% coverage`],['Ongoing Works',ongoing,'Official Sheet1'],['Works with MR',mr,'Screen 2 / Sheet1'],['Labour Engagement',labour,'Screen 2 / Sheet1'],['Muster Rolls',mrs,'Screen 2 / Sheet1']].map(x=>`<div class="kpi"><small>${x[0]}</small><strong>${fmt(x[1])}</strong><em>${x[2]}</em></div>`).join('');return}const gps=sum(list,'gps'),prog=sum(list,'gpsProgress'),ongoing=sum(list,'ongoing'),mr=sum(list,'worksMR'),labour=sum(list,'labour'),mrs=sum(list,'mrs');$('kpis').innerHTML=[['Gram Panchayats',gps,'Total GP'],['GPs with Progress',prog,`${pct(prog,gps).toFixed(1)}% coverage`],['Ongoing Works',ongoing,'Work load'],['Works with MR',mr,`${pct(mr,ongoing).toFixed(1)}% of ongoing`],['Labour Engagement',labour,'e-Muster based'],['Muster Rolls',mrs,'MR count']].map(x=>`<div class="kpi"><small>${x[0]}</small><strong>${fmt(x[1])}</strong><em>${x[2]}</em></div>`).join('')}
function aggregate(a,keys,metrics){const m=new Map();for(const r of a){const id=keys.map(k=>clean(r[k])).join('¦');if(!m.has(id)){const z={};keys.forEach(k=>z[k]=clean(r[k]));metrics.forEach(k=>z[k]=0);m.set(id,z)}const z=m.get(id);metrics.forEach(k=>z[k]+=num(r[k]))}return [...m.values()]}
function mixMap(){const m=new Map();for(const r of workmix){const k=[r.janpad,r.engineer,r.cluster,r.panchayat].map(clean).join('¦');m.set(k,r)}return m}
function apportionExact(group,key,target,fallbackKey='gps'){target=Math.max(0,Math.round(num(target)));if(!group.length)return;const vals=group.map(r=>Math.max(0,num(r[key]))),sumv=vals.reduce((a,b)=>a+b,0);let weights=vals;if(sumv<=0){weights=group.map(r=>Math.max(0,num(r[fallbackKey])));if(weights.reduce((a,b)=>a+b,0)<=0)weights=group.map(()=>1)}const sw=weights.reduce((a,b)=>a+b,0)||1;const raw=weights.map(w=>target*w/sw),base=raw.map(Math.floor);let left=target-base.reduce((a,b)=>a+b,0);const order=raw.map((v,i)=>({i,frac:v-base[i],name:clean(group[i].engineer)})).sort((a,b)=>b.frac-a.frac||a.name.localeCompare(b.name,'hi'));for(let n=0;n<left;n++)base[order[n%order.length].i]++;group.forEach((r,i)=>r[key]=base[i])}
function engineerData(list){const mm=mixMap();const enriched=list.map(r=>{const x=mm.get([r.janpad,r.engineer,r.cluster,r.panchayat].map(clean).join('¦'))||{};return {...r,pmayOngoing:num(x.pmayOngoing),ekOngoing:num(x.ekOngoing),currentFYActive:num(x.currentFYActive)}});const metrics=['gps','gpsProgress','ongoing','worksMR','labour','mrs','noEkyc','pmayOngoing','ekOngoing','currentFYActive'];const out=aggregate(enriched,['janpad','engineer'],metrics);const cm=new Map();for(const r of enriched){const k=[clean(r.janpad),clean(r.engineer)].join('¦');if(!cm.has(k))cm.set(k,new Set());if(clean(r.cluster))cm.get(k).add(clean(r.cluster));}for(const r of out){const k=[clean(r.janpad),clean(r.engineer)].join('¦');r.cluster=[...(cm.get(k)||[])].sort((a,b)=>a.localeCompare(b,'hi')).join(', ');}/* Reconcile Engineer-wise daily columns to official Sheet1 Janpad totals. RepDay remains the distribution basis, but each Janpad now sums exactly to Screen-2 / Sheet1. */const dmap=new Map(daily.map(r=>[normJanpad(r.janpad),r])),omap=new Map(official.map(r=>[normJanpad(r.janpad),r]));for(const j of [...new Set(out.map(r=>normJanpad(r.janpad)))]){const g=out.filter(r=>normJanpad(r.janpad)===j),d=dmap.get(j)||{},o=omap.get(j)||{};apportionExact(g,'gps',d.totalGP,'gps');apportionExact(g,'gpsProgress',d.gpsProgress,'gps');apportionExact(g,'labour',d.labour,'gps');apportionExact(g,'worksMR',d.worksMR,'ongoing');apportionExact(g,'mrs',d.mrs,'worksMR');apportionExact(g,'ongoing',o.ongoingAll,'gps')}return out}
function coverageBadgeText(worksMR,ongoing){return `${pct(worksMR,ongoing).toFixed(1)}%`}
function dysfunctionalEngineerData(list){
  /* Engineer-wise Dysfunctional GP is reconciled from Official Sheet1:
     Dysfunctional GP = Total GP - GP Progress. engineerData() already apportions
     GP and GP Progress so every Janpad exactly matches Screen-2 / Sheet1. */
  const eng=engineerData(list).filter(r=>num(r.gps)>0);
  const janpads=[...new Set(eng.map(r=>clean(r.janpad)).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'hi'));
  const out=[];
  for(const janpad of janpads){
    const group=eng.filter(r=>clean(r.janpad)===janpad).map(r=>({...r,dysfunctionalGP:Math.max(0,num(r.gps)-num(r.gpsProgress))}));
    const off=official.find(r=>normJanpad(r.janpad)===normJanpad(janpad));
    const janpadTotal=off?num(off.dysfunctionalGP):group.reduce((a,r)=>a+num(r.dysfunctionalGP),0);
    group.sort((a,b)=>num(b.dysfunctionalGP)-num(a.dysfunctionalGP)||pct(a.worksMR,a.ongoing)-pct(b.worksMR,b.ongoing)||num(b.ongoing)-num(a.ongoing)||clean(a.engineer).localeCompare(clean(b.engineer),'hi'));
    group.forEach((r,i)=>out.push({...r,rank:i+1,totalJanpadDys:janpadTotal}));
  }
  return out;
}
function alertInsights(list){
  const eng=engineerData(list).filter(r=>num(r.ongoing)>0);
  const janpads=[...new Set(eng.map(r=>clean(r.janpad)).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'hi'));
  const lowByJanpad=[];
  for(const janpad of janpads){
    const je=eng.filter(r=>clean(r.janpad)===janpad)
      .sort((a,b)=>pct(a.worksMR,a.ongoing)-pct(b.worksMR,b.ongoing)||num(b.ongoing)-num(a.ongoing)||clean(a.engineer).localeCompare(clean(b.engineer),'hi'))
      .slice(0,3);
    if(je.length)lowByJanpad.push({janpad,items:je});
  }
  const allDys=dysfunctionalEngineerData(list),dysByJanpad=[];
  for(const janpad of [...new Set(allDys.map(r=>r.janpad))]){
    const all=allDys.filter(r=>r.janpad===janpad),items=all.filter(r=>num(r.dysfunctionalGP)>0).slice(0,3);
    if(items.length)dysByJanpad.push({janpad,items,totalDys:all.length?all[0].totalJanpadDys:0});
  }
  return {lowByJanpad,dysByJanpad};
}
function renderAlerts(list){
  const el=$('alerts');if(!el)return;
  const {lowByJanpad,dysByJanpad}=alertInsights(list);
  const lowRows=[];for(const g of lowByJanpad){g.items.forEach((x,i)=>lowRows.push(`<tr><td>${esc(g.janpad)}</td><td class="rank-cell">${i+1}</td><td>${esc(x.engineer)}</td><td>${esc(x.cluster||'—')}</td><td>${fmt(x.ongoing)}</td><td>${fmt(x.worksMR)}</td><td><span class="mini-chip warn-chip">${coverageBadgeText(x.worksMR,x.ongoing)}</span></td></tr>`))}
  const lowHtml=lowRows.length?`<div class="alert-table-wrap"><table class="alert-table"><thead><tr><th>Janpad</th><th>Rank</th><th>Sub Engineer</th><th>Cluster(s)</th><th>Ongoing</th><th>Works with MR</th><th>MR %</th></tr></thead><tbody>${lowRows.join('')}</tbody></table></div>`:`<div class="empty-alert">Current filter में data उपलब्ध नहीं है।</div>`;
  const dysRows=[];for(const g of dysByJanpad){g.items.forEach((x,i)=>{dysRows.push(`<tr><td>${esc(g.janpad)}</td><td class="rank-cell dys-rank">${i+1}</td><td>${esc(x.engineer)}</td><td>${esc(x.cluster||'—')}</td><td>${fmt(x.gps)}</td><td>${fmt(x.gpsProgress)}</td><td class="dys-count">${fmt(x.dysfunctionalGP)}</td><td>${fmt(g.totalDys)}</td></tr>`)})}
  const dysHtml=dysRows.length?`<div class="alert-table-wrap"><table class="alert-table dys-alert-table"><thead><tr><th>Janpad</th><th>Rank</th><th>Sub Engineer</th><th>Cluster(s)</th><th>Total GP</th><th>GP Progress</th><th>Dys GP</th><th>Janpad Official Dys GP</th></tr></thead><tbody>${dysRows.join('')}</tbody></table></div>`:`<div class="empty-alert">Current filter में कोई dysfunctional GP नहीं मिला।</div>`;
  el.innerHTML=`<article class="alert-card warn wide"><div class="alert-head"><span class="alert-icon">⚠</span><div><h3>Per Janpad — 03 Sub Engineer: Lowest MR Coverage</h3><p>हर Janpad के 3 सबसे कम Muster Roll coverage वाले Sub Engineer</p></div></div>${lowHtml}</article><article class="alert-card danger wide"><div class="alert-head"><span class="alert-icon">📍</span><div><h3>Per Janpad — 03 Sub Engineer: Dysfunctional GP Alert</h3><p>Official Sheet1 के अनुसार Engineer-wise Dysfunctional GP = Total GP − GP Progress; Janpad total Screen-2 से exact match</p></div></div>${dysHtml}</article>`;
}
function dysfunctionalAlertTable(list){
  return dysfunctionalEngineerData(list).filter(r=>num(r.dysfunctionalGP)>0).map(r=>({janpad:r.janpad,rank:r.rank,engineer:r.engineer,cluster:r.cluster,totalGP:r.gps,gpProgress:r.gpsProgress,dysfunctionalGP:r.dysfunctionalGP,ongoing:r.ongoing,worksMR:r.worksMR,labour:r.labour,mrCoverage:+pct(r.worksMR,r.ongoing).toFixed(1),totalJanpadDys:r.totalJanpadDys}));
}
function renderDysfunctionalBucket(list){
  const data=dysfunctionalAlertTable(list);lastExport=data;
  $('viewTitle').textContent='Engineer-wise Dysfunctional GP — Official Reconciled';
  $('viewMeta').textContent=`Dysfunctional GP = Total GP − GP Progress • Janpad totals Official Sheet1 / Screen-2 matched • ${todayDate()}`;
  let h=`<thead><tr><th>Janpad</th><th>Rank</th><th>Sub Engineer</th><th>Cluster(s)</th><th>Total GP</th><th>GP Progress</th><th>Dysfunctional GP</th><th>Ongoing Works</th><th>Works with MR</th><th>Labour</th><th>MR Coverage</th><th>Janpad Official Dys GP</th></tr></thead><tbody>`;
  for(const r of data){h+=`<tr>${cell(r.janpad)}${cell(r.rank,true)}${cell(r.engineer)}${cell(r.cluster)}${cell(r.totalGP,true)}${cell(r.gpProgress,true)}${cell(r.dysfunctionalGP,true)}${cell(r.ongoing,true)}${cell(r.worksMR,true)}${cell(r.labour,true)}<td>${r.mrCoverage.toFixed(1)}%</td>${cell(r.totalJanpadDys,true)}</tr>`}
  if(!data.length)h+=`<tr><td colspan="12" class="empty-table">Current filter में कोई Dysfunctional GP नहीं मिला।</td></tr>`;
  h+=`</tbody>`;$('reportTable').innerHTML=h;
}
function priorityAlertTable(list){
  const out=[];
  for(const r of list){
    const ongoing=num(r.ongoing),worksMR=num(r.worksMR),labour=num(r.labour),mrs=num(r.mrs),cover=pct(worksMR,ongoing);
    if(ongoing<=0)continue;
    let severity='',alert='';
    if(worksMR===0){severity='CRITICAL';alert='Ongoing work है लेकिन MR issued work 0';}
    else if(labour===0){severity='HIGH';alert='Ongoing work है लेकिन Labour Engagement 0';}
    else if(cover<10){severity='HIGH';alert='MR Coverage 10% से कम';}
    else if(cover<20){severity='WATCH';alert='MR Coverage 20% से कम';}
    else continue;
    out.push({severity,alert,janpad:r.janpad,engineer:r.engineer,cluster:r.cluster,panchayat:r.panchayat,ongoing,worksMR,mrCoverage:+cover.toFixed(1),labour,mrs});
  }
  const w={CRITICAL:0,HIGH:1,WATCH:2};
  return out.sort((a,b)=>w[a.severity]-w[b.severity]||a.mrCoverage-b.mrCoverage||b.ongoing-a.ongoing||clean(a.janpad).localeCompare(clean(b.janpad),'hi')||clean(a.panchayat).localeCompare(clean(b.panchayat),'hi'));
}
function renderPriorityAlerts(list){
  const data=priorityAlertTable(list);lastExport=data;
  const critical=data.filter(r=>r.severity==='CRITICAL').length,high=data.filter(r=>r.severity==='HIGH').length,watch=data.filter(r=>r.severity==='WATCH').length;
  $('viewTitle').textContent='Priority Alerts — GP Action List';
  $('viewMeta').textContent=`Critical ${fmt(critical)} • High ${fmt(high)} • Watch ${fmt(watch)} • ${todayDate()}`;
  let h=`<thead><tr><th>Priority</th><th>Alert Reason</th><th>Janpad</th><th>Sub Engineer</th><th>Cluster</th><th>Gram Panchayat</th><th>Ongoing</th><th>Works with MR</th><th>MR %</th><th>Labour</th><th>Muster Rolls</th></tr></thead><tbody>`;
  for(const r of data){h+=`<tr><td><span class="priority-chip ${r.severity.toLowerCase()}">${esc(r.severity)}</span></td><td class="alert-reason-cell">${esc(r.alert)}</td>${cell(r.janpad)}${cell(r.engineer)}${cell(r.cluster)}${cell(r.panchayat)}${cell(r.ongoing,true)}${cell(r.worksMR,true)}<td>${r.mrCoverage.toFixed(1)}%</td>${cell(r.labour,true)}${cell(r.mrs,true)}</tr>`}
  if(!data.length)h+=`<tr><td colspan="11" class="empty-table">Current filter में कोई Priority Alert नहीं मिला।</td></tr>`;
  h+='</tbody>';$('reportTable').innerHTML=h;
}
function dysfunctionalAlertTable(list){const {dysByJanpad}=alertInsights(list);const flat=[];for(const group of dysByJanpad){group.items.forEach((x,i)=>flat.push({janpad:group.janpad,rank:i+1,engineer:x.engineer,cluster:x.cluster,dysfunctionalGP:x.count,gpNames:x.gps.map(v=>`${v.name} (${fmt(v.ongoing)})`).join(', '),ongoing:x.ongoing,totalJanpadDys:group.totalDys}))}return flat}
function renderDysfunctionalBucket(list){const data=dysfunctionalAlertTable(list);lastExport=data;$('viewTitle').textContent='Per Janpad — 03 Sub Engineer: Dysfunctional GP Alert';$('viewMeta').textContent=`हर Janpad के Top 3 Sub Engineer • ${todayDate()}`;let h=`<thead><tr><th>Janpad</th><th>Rank</th><th>Sub Engineer</th><th>Cluster</th><th>Dysfunctional GP</th><th>GP Name (Ongoing Work)</th><th>Ongoing Works</th><th>Janpad Total Dys GP</th></tr></thead><tbody>`;for(const r of data){h+=`<tr>${cell(r.janpad)}${cell(r.rank,true)}${cell(r.engineer)}${cell(r.cluster)}${cell(r.dysfunctionalGP,true)}<td class="gp-name-cell">${esc(r.gpNames)}</td>${cell(r.ongoing,true)}${cell(r.totalJanpadDys,true)}</tr>`}if(!data.length)h+=`<tr><td colspan="8" class="empty-table">Current filter में कोई Dysfunctional GP नहीं मिला।</td></tr>`;h+=`</tbody>`;$('reportTable').innerHTML=h}
function officialFiltered(){let a=official;if($('districtFilter').value!=='ALL')a=a.filter(r=>districtOf(r.janpad)===$('districtFilter').value);if($('janpadFilter').value!=='ALL')a=a.filter(r=>r.janpad===$('janpadFilter').value);return a}

function finalWorkCategory(name,wt,fy){
 const n=clean(name),w=clean(wt),t=(n+' '+w).toLowerCase(),start=n.toLowerCase().trim();
 const has=(re)=>re.test(t), starts=(re)=>re.test(start);
 // Housing / beneficiary house stays protected.
 if(/pmay|pmay[- ]?g|pradhan\s*mantri\s*awas/i.test(w)||/pmay|pmay[- ]?g/i.test(n))return 'PMAY-G';
 // Strict Ek Bagiya rule: FY 2025-26/2026-27, actual title starts with Bagiya phrase, not school/institution context.
 const inst=/(school|prathmik|madhyamik|shala|vidyalaya|प्राथमिक|माध्यमिक|शाला|विद्यालय)/i;
 const ekStart=/^(?:ek\s+(?:ma+a?|maa|mother)?\s*ki?\s*)?(?:bagiya|bagia)|^ek\s+bagiya|^ek\s+(?:maa?|ma|mाँ|मॉ|माॅ)\s+ke\s+naam|^(?:एक\s+)?(?:माँ|मा|मॉ|माॅ)\s*(?:की|के\s+नाम)?\s*बगिया|^एक\s+बगिया/i;
 if(['2025-2026','2026-2027'].includes(clean(fy))&&ekStart.test(n)&&!inst.test(n))return 'Ek Bagiya';
 // Strong actual-work priorities: location words later in the title must not override these.
 if(has(/(?:boundary|boundry|boundri|baundri|baundry|bawandri|bawndri|baudri|baundary|baun?dr[iy]|बाउंड्री|बाउण्डी|बाउण्?डी|बाउणडी|बाउंडरी|बॉउंड्री)/i))return 'Boundary Wall';
 if(has(/(?:puliya|pulia|pulya|पुलिया|culvert|cluvert|hume\s*pipe|क्रांस|cross)/i))return 'Pulya';
 if(has(/(?:pcc|cc|cement\s*concrete|concrete|nali|नाली|drain|drainage|grey\s*water|greywater|ग्रेवाटर|cover(?:e)?d\s*nali|rural\s*connectivity)/i))return 'Cement Concrete';
 if(has(/(?:gravel|greval|grewal|graval|grable|ग्रेवल|ग्रेबल|गे्रवल|गे्वल|mitti\s*mur+am|mur+am|murram|मिट्टी\s*मुरुम|मुरुम|sudoor|sudur|सुदूर\s*सड़क|bt\s*road|बीटी\s*रोड|bitumen)/i))return 'Gravel Road';
 if(has(/(?:r\.?m\.?s\.?|आर\.?एम\.?एस|stop\s*dam|stap\s*dam|स्टाप\s*डैम|स्टापडैम|स्टाप\s*डेम|check\s*dam|चेक\s*डैम|ring\s*bund|d\s*frame|d\s*band|percolation|parkulation|पार्कुलेशन|hand\s*pump\s*recharge|handpump\s*recharge|hundpump\s*recharge)/i))return 'Water conservation & recharge';
 if(has(/(?:khet\s*talab|खेत\s*तालाब|ctr.*khet\s*talab|farm\s*pond)/i))return 'Farm Pond';
 if(has(/(?:dug\s*pond|डुग\s*पोंड|डग\s*पोंड|soak\s*pit|soakpit|shokpit|शोकपिट|gabion|rfr|nadi\s*restoration|gully\s*plug|medh\s*bandhan|loose\s*boulder|new\s*talab)/i))return 'Watershed Related Works';
 if(has(/(?:samuday(?:i|ik|ak)\s*koop|community\s*well|सामुदायिक\s*कूप|dug\s*well\s*recharge|dugwell\s*recharge)/i))return 'Dug Well Recharge';
 if(has(/(?:charagah|charagaah|chara\s*gah|chara\s*gaah|चारागाह|चारगाह|चारा\s*गाह|posh?an\s*vatika|vasudha|vashudha|bsudha|vassudha|वसुधा|vriksharopan|vraksha\s*ropan|bracharopan|braksharopan|वृक्षारोपण|व़क्षारोपण|वुक्षारोपण|faloudd?yan|faloudyan|फलोउद्यान|फलोउद्ययान|plantation|land\s*development)/i))return 'Gap Filling in Plantation';
 if(has(/(?:shanti\s*dham|santi\s*dham|santhi\s*dham|shathi\s*dham|shanti\s*daham|shantidham|shantidam|mukti\s*dham|muktidham|मुक्तिधाम|शांति\s*धाम|शांती\s*धाम|शान्ति\s*धाम|शान्तिधाम)/i))return 'Crematorium';
 if(has(/(?:panchayat\s*bhavan|panchyat\s*bhawan|panchyat\s*bhavan|naveen\s*panchayat|mangal\s*bhawan|samudai?k\s*bhawan|samudayik\s*bhavan|samudaik\s*bhavan|sabhagar\s*nirman|kaushal|कौशल|मंगल\s*भवन|पंचायत\s*भवन|सामुदायिक\s*भवन)/i))return 'Panchayat and Community Hall';
 if(has(/(?:samudai?k\s*shauchalay|samudayik\s*shauchalay|सामुदायिक\s*शौचालय|segregation|segragation|kachara|karchra|kooda|kuda|कचरा|कूड़ा|nadep)/i))return 'SBM Works';
 if(has(/(?:play\s*ground|playground|khel\s*maidan|खेल\s*मैदान|खेल\s*का\s*मैदान|खेलो\s*के\s*मैदान)/i))return 'Play Field';
 const angStart=/^(?:a+nganwadi|a+ganwadi|a+anganbadi|a+ganbadi|anganbadi|aganbadi|आंगनवाडी|आंगनवाड़ी|आंगनवाड़ी|आंगनबाडी|आंगनबाड़ी|आंगनबाड़ी|आगनबाडी|आगनबाड़ी|आगनबाड़ी|आगनवाडी|आगनवाड़ी|आगनवाड़ी|आगवाड़ी|आगवाडी|ऑगनबाडी|ऑगनबाड़ी|ऑगनबाड़ी|ऑगनवाडी|ऑगनवाड़ी|ऑगनवाड़ी|अांगनवाडी|आंंगनवाडी)/i;
 if(starts(angStart)&&has(/(?:bhavan|bhawan|nirman|kendra|sewa\s*kendra|शेष\s*कार्य|कार्य|भवन|निर्माण|केंद्र)/i))return 'Anganwadi';
 if(has(/(?:kapil\s*dhara|kapildhara|कपिलधारा|open\s*dug\s*well|open\s*dugwell)/i))return 'Kapildhara';
 if(has(/(?:cattle\s*shed|goat\s*shelter|poultry|pasu\s*shed|pashu\s*shed|पशु\s*शेड)/i))return 'Poultry Cattle and Goat Shelter';
 if(has(/(?:micro\s*irrigation|सूक्ष्म\s*सिंचाई)/i))return 'Irrigation infrastructure';
 // Protected / residual Other Works examples from the established rules.
 if(has(/(?:uchit\s*mul|उचित\s*मूल|pds|food\s*grain|foodgrain|khad[hy]*yan|खाद्यान|खय्दायन|godam|gaushala|gau\s*shala|chabut|चबुत|paver|pever|pewar|retaining\s*wall|retarning\s*wall|ghat\s*nirman|bus\s*stop|pani\s*tanki|water\s*tank|kitchen\s*shed|laboratory|प्रयोगशाला|sub\s*health|उप\s*स्वास्थ्य|rangmanch|park|paper)/i))return 'Other Works';
 // Normalize common raw work types when the name itself is sparse.
 const rw=w.toLowerCase();
 if(/crematorium/.test(rw))return 'Crematorium';
 if(/plantation|chara\s*gaah/.test(rw))return 'Gap Filling in Plantation';
 if(/check\s*dam|percolation/.test(rw))return 'Water conservation & recharge';
 if(/khet\s*talab|farm\s*pond/.test(rw))return 'Farm Pond';
 if(/dug\s*pond|soak\s*pit|gully\s*plug/.test(rw))return 'Watershed Related Works';
 if(/play\s*ground/.test(rw))return 'Play Field';
 if(/pcc|coverd\s*nali/.test(rw))return 'Cement Concrete';
 if(/puliya|pulya/.test(rw))return 'Pulya';
 if(/boundary/.test(rw))return 'Boundary Wall';
 if(/cattle\s*shed/.test(rw))return 'Poultry Cattle and Goat Shelter';
 if(/nadep|segregation|\bcsc\b/.test(rw))return 'SBM Works';
 if(/old\s*water|amrit\s*sarovar|roof\s*top/.test(rw))return 'Water conservation & recharge';
 if(/contour\s*trench|loose\s*bolder|loose\s*boulder|nala\s*trench/.test(rw))return 'Watershed Related Works';
 if(/panchayat.*community.*bhawan|community.*bhawan/.test(rw))return 'Panchayat and Community Hall';
 if(/other/.test(rw))return 'Other Works';
 return w||'Other Works';
}
function categoryFiltered(){const d=$('districtFilter').value,j=$('janpadFilter').value,e=$('engineerFilter').value,c=$('clusterFilter').value;return categorymix.filter(r=>(d==='ALL'||districtOf(r.janpad)===d)&&(j==='ALL'||r.janpad===j)&&(e==='ALL'||r.engineer===e)&&(c==='ALL'||r.cluster===c))}
function moneyLakh(v){return (num(v)/100000).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}
function renderCategoryBuckets(){const src=categoryFiltered();const data=aggregate(src,['category'],['workCount','totalSanction','totalBooked','b0','b25','b60','b75','b90','b90p']).sort((a,b)=>num(b.workCount)-num(a.workCount)||clean(a.category).localeCompare(clean(b.category),'hi'));data.forEach(r=>r.expPct=r.totalSanction?num(r.totalBooked)*100/num(r.totalSanction):0);lastExport=data;$('viewTitle').textContent='Final Category-wise Ongoing Work Buckets';$('viewMeta').textContent=`${fmt(data.length)} Final Categories • Established Final Work Category Rules • Expenditure = Booked Since Inception ÷ Total Sanction • ${todayDate()}`;let h=`<thead><tr><th>Work Category</th><th>Total Works</th><th>0%</th><th>1%–25%</th><th>26%–60%</th><th>61%–75%</th><th>76%–90%</th><th>&gt;90%</th><th>Sanction ₹ Lakh</th><th>Booked ₹ Lakh</th><th>Exp %</th></tr></thead><tbody>`;for(const r of data){h+=`<tr>${cell(r.category)}${cell(r.workCount,true)}<td class="bucket-zero">${fmt(r.b0)}</td>${cell(r.b25,true)}${cell(r.b60,true)}${cell(r.b75,true)}${cell(r.b90,true)}<td class="bucket-good">${fmt(r.b90p)}</td><td>${moneyLakh(r.totalSanction)}</td><td>${moneyLakh(r.totalBooked)}</td><td><span class="exp-pct-chip ${r.expPct===0?'critical':r.expPct<=25?'low':r.expPct>90?'good':''}">${r.expPct.toFixed(1)}%</span></td></tr>`}const t={};['workCount','totalSanction','totalBooked','b0','b25','b60','b75','b90','b90p'].forEach(k=>t[k]=sum(data,k));const ep=t.totalSanction?t.totalBooked*100/t.totalSanction:0;h+=`<tr class="total-row"><td>TOTAL</td>${cell(t.workCount,true)}${cell(t.b0,true)}${cell(t.b25,true)}${cell(t.b60,true)}${cell(t.b75,true)}${cell(t.b90,true)}${cell(t.b90p,true)}<td>${moneyLakh(t.totalSanction)}</td><td>${moneyLakh(t.totalBooked)}</td><td>${ep.toFixed(1)}%</td></tr>`;if(!data.length)h+=`<tr><td colspan="11" class="empty-table">Current filter में Category data नहीं मिला।</td></tr>`;h+='</tbody>';$('reportTable').innerHTML=h}
function renderExpBuckets(){const src=categoryFiltered();const data=aggregate(src,['janpad','engineer','cluster'],['workCount','b0','b25','b60','b75','b90','b90p','totalSanction','totalBooked']).sort((a,b)=>num(b.b0)-num(a.b0)||num(b.workCount)-num(a.workCount)||clean(a.janpad).localeCompare(clean(b.janpad),'hi')||clean(a.engineer).localeCompare(clean(b.engineer),'hi'));data.forEach(r=>r.expPct=r.totalSanction?num(r.totalBooked)*100/num(r.totalSanction):0);lastExport=data;$('viewTitle').textContent='Expenditure % — Ongoing Work Buckets';$('viewMeta').textContent=`0% को Critical priority • 1–25% Low expenditure • ${todayDate()}`;let h=`<thead><tr><th>Janpad</th><th>Sub Engineer</th><th>Cluster</th><th>Total Works</th><th>0%</th><th>1%–25%</th><th>26%–60%</th><th>61%–75%</th><th>76%–90%</th><th>&gt;90%</th><th>Overall Exp %</th></tr></thead><tbody>`;for(const r of data){h+=`<tr>${cell(r.janpad)}${cell(r.engineer)}${cell(r.cluster)}${cell(r.workCount,true)}<td class="bucket-zero">${fmt(r.b0)}</td>${cell(r.b25,true)}${cell(r.b60,true)}${cell(r.b75,true)}${cell(r.b90,true)}<td class="bucket-good">${fmt(r.b90p)}</td><td><span class="exp-pct-chip ${r.expPct===0?'critical':r.expPct<=25?'low':r.expPct>90?'good':''}">${r.expPct.toFixed(1)}%</span></td></tr>`}const t={};['workCount','b0','b25','b60','b75','b90','b90p','totalSanction','totalBooked'].forEach(k=>t[k]=sum(data,k));const ep=t.totalSanction?t.totalBooked*100/t.totalSanction:0;h+=`<tr class="total-row"><td>TOTAL</td><td></td><td></td>${cell(t.workCount,true)}${cell(t.b0,true)}${cell(t.b25,true)}${cell(t.b60,true)}${cell(t.b75,true)}${cell(t.b90,true)}${cell(t.b90p,true)}<td>${ep.toFixed(1)}%</td></tr>`;if(!data.length)h+=`<tr><td colspan="11" class="empty-table">Current filter में expenditure bucket data नहीं मिला।</td></tr>`;h+='</tbody>';$('reportTable').innerHTML=h}
function cell(v,isnum=false){return `<td>${isnum?fmt(v):esc(v)}</td>`}function badge(a,b){const p=pct(a,b);return `<span class="badge ${p>=10?'good':'warn'}">${p.toFixed(1)}%</span>`}
function renderOfficial(){const data=officialFiltered();lastExport=data;$('viewTitle').textContent='Official Janpad Daily Report';$('viewMeta').textContent=`${data.length} Janpad • ${todayDate()}`;let h=`<thead><tr><th rowspan="2">District</th><th rowspan="2">Janpad</th><th colspan="3">Gram Panchayat</th><th colspan="4">All Types of Works</th><th colspan="2">Individual Land (Cat-IV)</th><th colspan="3">Community Works</th><th colspan="3">PMAY-G</th><th colspan="4">Ek Bagiya</th></tr><tr><th>Total GP</th><th>Muster GP</th><th>Dysfunctional</th><th>Labour</th><th>Works with MR</th><th>Ongoing</th><th>MR %</th><th>Labour</th><th>Works MR</th><th>Labour</th><th>Works MR</th><th>Share %</th><th>Ongoing</th><th>MR Issued</th><th>MR %</th><th>Labour</th><th>Ongoing</th><th>MR Issued</th><th>MR %</th></tr></thead><tbody>`;for(const r of data){h+=`<tr>${cell(districtOf(r.janpad))}${cell(r.janpad)}${cell(r.totalGP,true)}${cell(r.musterGP,true)}${cell(r.dysfunctionalGP,true)}${cell(r.labourAll,true)}${cell(r.mrAll,true)}${cell(r.ongoingAll,true)}<td>${badge(r.mrAll,r.ongoingAll)}</td>${cell(r.labourIndividual,true)}${cell(r.mrIndividual,true)}${cell(r.labourCommunity,true)}${cell(r.mrCommunity,true)}<td>${badge(r.mrCommunity,r.mrAll)}</td>${cell(r.pmayOngoing,true)}${cell(r.pmayMR,true)}<td>${badge(r.pmayMR,r.pmayOngoing)}</td>${cell(r.ekLabour,true)}${cell(r.ekOngoing,true)}${cell(r.ekMR,true)}<td>${badge(r.ekMR,r.ekOngoing)}</td></tr>`}const keys=['totalGP','musterGP','dysfunctionalGP','labourAll','mrAll','ongoingAll','labourIndividual','mrIndividual','labourCommunity','mrCommunity','pmayOngoing','pmayMR','ekLabour','ekOngoing','ekMR'],t={};keys.forEach(k=>t[k]=sum(data,k));h+=`<tr class="total-row"><td>TOTAL</td><td></td>${cell(t.totalGP,true)}${cell(t.musterGP,true)}${cell(t.dysfunctionalGP,true)}${cell(t.labourAll,true)}${cell(t.mrAll,true)}${cell(t.ongoingAll,true)}<td>${pct(t.mrAll,t.ongoingAll).toFixed(1)}%</td>${cell(t.labourIndividual,true)}${cell(t.mrIndividual,true)}${cell(t.labourCommunity,true)}${cell(t.mrCommunity,true)}<td>${pct(t.mrCommunity,t.mrAll).toFixed(1)}%</td>${cell(t.pmayOngoing,true)}${cell(t.pmayMR,true)}<td>${pct(t.pmayMR,t.pmayOngoing).toFixed(1)}%</td>${cell(t.ekLabour,true)}${cell(t.ekOngoing,true)}${cell(t.ekMR,true)}<td>${pct(t.ekMR,t.ekOngoing).toFixed(1)}%</td></tr></tbody>`;$('reportTable').innerHTML=h}
function standardTable(data,cols,title){lastExport=data;$('viewTitle').textContent=title;$('viewMeta').textContent=`${fmt(data.length)} rows • ${todayDate()}`;const nums=new Set(cols.filter(x=>x[2]).map(x=>x[0]));let h='<thead><tr>'+cols.map(c=>`<th>${c[1]}</th>`).join('')+'<th>MR Coverage</th></tr></thead><tbody>';for(const r of data){h+='<tr>'+cols.map(c=>cell(r[c[0]],nums.has(c[0]))).join('')+`<td>${badge(r.worksMR,r.ongoing)}</td></tr>`}const total={};nums.forEach(k=>total[k]=sum(data,k));h+=`<tr class="total-row">${cols.map((c,i)=>`<td>${i===0?'TOTAL':nums.has(c[0])?fmt(total[c[0]]):''}</td>`).join('')}<td>${pct(total.worksMR,total.ongoing).toFixed(1)}%</td></tr></tbody>`;$('reportTable').innerHTML=h}
function render(){const list=filteredRows();$('reportDate').textContent=todayDate();kpis(list);renderAlerts(list);$('reportTable').className='report-table '+(view==='official'?'official-grid':view==='engineer'?'engineer-grid':view==='district'?'district-grid':view==='priority'?'priority-grid':view==='dysfunctional'?'dysfunctional-grid':view==='category'?'category-grid':view==='expbucket'?'expbucket-grid':'gp-grid');if(view==='official')return renderOfficial();if(view==='category')return renderCategoryBuckets();if(view==='expbucket')return renderExpBuckets();if(view==='priority')return renderPriorityAlerts(list);if(view==='dysfunctional')return renderDysfunctionalBucket(list);if(view==='engineer'){const d=engineerData(list);return standardTable(d.sort((a,b)=>clean(a.janpad).localeCompare(clean(b.janpad),'hi')||clean(a.engineer).localeCompare(clean(b.engineer),'hi')),[['janpad','Janpad'],['engineer','Engineer / Upyantri'],['cluster','Cluster(s)'],['gps','GP',1],['gpsProgress','GP Progress',1],['labour','Labour',1],['ongoing','Ongoing Works',1],['worksMR','Works with MR',1],['mrs','Muster Rolls',1],['pmayOngoing','PMAY-G Ongoing',1],['ekOngoing','Ek Bagiya Ongoing',1],['currentFYActive','Current FY Active Works',1]],'Engineer-wise Daily Report — Official Sheet1 Reconciled')}if(view==='district'){if($('engineerFilter').value==='ALL'&&$('clusterFilter').value==='ALL'&&daily.length){const dd=dailyFiltered().map(r=>({...r,district:districtOf(r.janpad)}));const d=aggregate(dd,['district'],['totalGP','gpsProgress','labour','worksMR','mrs','noEkyc']);const om=aggregate(officialFiltered().map(r=>({...r,district:districtOf(r.janpad)})),['district'],['ongoingAll']);const ox=new Map(om.map(r=>[r.district,r.ongoingAll]));d.forEach(r=>r.ongoing=ox.get(r.district)||0);return standardTable(d,[['district','District'],['totalGP','Total GP',1],['gpsProgress','GP Progress',1],['labour','Labour',1],['ongoing','Ongoing Works',1],['worksMR','Works with MR',1],['mrs','Muster Rolls',1]],'Full District Report — Screen 2 Matched')}const d=aggregate(list.map(r=>({...r,district:districtOf(r.janpad)})),['district'],['gps','gpsProgress','ongoing','worksMR','labour','mrs','noEkyc']);return standardTable(d,[['district','District'],['gps','Total GP',1],['gpsProgress','GP Progress',1],['labour','Labour',1],['ongoing','Ongoing Works',1],['worksMR','Works with MR',1],['mrs','Muster Rolls',1]],'Full District Report')}return standardTable(list,[['janpad','Janpad'],['engineer','Engineer'],['cluster','Cluster'],['panchayat','Gram Panchayat'],['labour','Labour',1],['ongoing','Ongoing Works',1],['worksMR','Works with MR',1],['mrs','Muster Rolls',1]],'Gram Panchayat Detail')}
function sheetArray(wb,name){const s=wb.Sheets[name];return s?XLSX.utils.sheet_to_json(s,{header:1,defval:''}):[]}
function parseWorkbook(wb){const a=sheetArray(wb,'RepDay');if(!a.length)throw new Error('RepDay sheet नहीं मिली।');reportTitle=clean(a?.[0]?.[0]);rows=[];for(let i=3;i<a.length;i++){const r=a[i];if(!clean(r[0])||!clean(r[1])||!clean(r[5]))continue;rows.push({janpad:normJanpad(r[0]),engineer:clean(r[1]),cluster:clean(r[2]),ongoing:num(r[3]),panchayat:clean(r[5]).toUpperCase(),gps:num(r[6]),gpsProgress:num(r[7]),labour:num(r[8]),worksMR:num(r[9]),noEkyc:num(r[10]),mrs:num(r[11])})}
 const s1=sheetArray(wb,'Sheet1');official=[];for(const ix of [3,4,5,7,8,9,10,11]){const r=s1[ix]||[];if(!clean(r[1]))continue;official.push({janpad:normJanpad(r[1]),totalGP:num(r[2]),musterGP:num(r[3]),dysfunctionalGP:num(r[4]),labourAll:num(r[5]),mrAll:num(r[6]),ongoingAll:num(r[7]),labourIndividual:num(r[9]),mrIndividual:num(r[10]),labourCommunity:num(r[11]),mrCommunity:num(r[12]),pmayOngoing:num(r[14]),pmayMR:num(r[15]),ekLabour:num(r[17]),ekOngoing:num(r[18]),ekMR:num(r[19])})}
 daily=[];let hix=s1.findIndex(r=>clean(r?.[2]).toLowerCase().includes('total no. of gram panchayats'));if(hix>=0){for(let i=hix+2;i<s1.length;i++){const r=s1[i]||[],j=clean(r[1]).toUpperCase();if(!j||j==='TOTAL')continue;if(!MAIHAR.has(j)&&!SATNA.has(j))continue;daily.push({janpad:j,totalGP:num(r[2]),gpsProgress:num(r[3]),labour:num(r[4]),worksMR:num(r[5]),noEkyc:num(r[6]),mrs:num(r[7])})}}
 const gpmap=new Map(rows.map(r=>[[r.janpad,r.panchayat].join('¦'),[r.engineer,r.cluster]]));workmix=[];categorymix=[];const wm=new Map(),cm=new Map(),v=sheetArray(wb,'VBG');const expBucket=p=>p<=0?'b0':p<=25?'b25':p<=60?'b60':p<=75?'b75':p<=90?'b90':'b90p';for(let i=4;i<v.length;i++){const r=v[i],jan=normJanpad(r[2]),gp=clean(r[3]).toUpperCase(),fy=clean(r[4]),status=clean(r[5]).toLowerCase(),code=clean(r[6]),name=clean(r[7]),wt=clean(r[8]);if(!jan||!gp||!code||!status.includes('ongoing'))continue;const ec=gpmap.get([jan,gp].join('¦'))||['Unmapped','Unmapped'],key=[jan,ec[0],ec[1],gp].join('¦');if(!wm.has(key))wm.set(key,{janpad:jan,engineer:ec[0],cluster:ec[1],panchayat:gp,workTotal:0,pmayOngoing:0,ekOngoing:0,currentFYActive:0});const z=wm.get(key);z.workTotal++;if(wt.toLowerCase().includes('pmay'))z.pmayOngoing++;if(finalWorkCategory(name,wt,fy)==='Ek Bagiya')z.ekOngoing++;if(num(r[21])>0)z.currentFYActive++;const cat=finalWorkCategory(name,wt,fy),sanction=num(r[11])||num(r[9])+num(r[10]),booked=num(r[16])+num(r[17]),ep=sanction?booked*100/sanction:0,ck=[jan,ec[0],ec[1],gp,cat].join('¦');if(!cm.has(ck))cm.set(ck,{janpad:jan,engineer:ec[0],cluster:ec[1],panchayat:gp,category:cat,workCount:0,totalSanction:0,totalBooked:0,b0:0,b25:0,b60:0,b75:0,b90:0,b90p:0});const q=cm.get(ck);q.workCount++;q.totalSanction+=sanction;q.totalBooked+=booked;q[expBucket(ep)]++}workmix=[...wm.values()];categorymix=[...cm.values()];if(!rows.length)throw new Error('RepDay में usable data नहीं मिला।')}
$('fileInput').addEventListener('change',e=>{pendingFile=e.target.files[0]||null;$('fileStatus').textContent=pendingFile?`Selected: ${pendingFile.name}`:'कोई file नहीं चुनी गई'});$('generateBtn').addEventListener('click',async()=>{if(!pendingFile){render();return}try{if(typeof XLSX==='undefined')throw new Error('Excel reader load नहीं हुआ।');$('fileStatus').textContent='Excel पढ़ी जा रही है…';const buf=await pendingFile.arrayBuffer();parseWorkbook(XLSX.read(buf,{type:'array'}));autoMeta={mode:'manual',updatedAt:new Date().toISOString(),source:pendingFile.name,status:'manual'};refreshFilters();render();updateAutoStatus();updateAutoStatus();$('fileStatus').textContent=`Generated: ${pendingFile.name} • ${fmt(rows.length)} GP rows`}catch(e){$('fileStatus').textContent='Error: '+e.message;alert(e.message)}});
['districtFilter','janpadFilter','engineerFilter','clusterFilter'].forEach(id=>$(id).addEventListener('change',()=>{refreshFilters();render()}));$('resetBtn').addEventListener('click',()=>{$('districtFilter').value='ALL';refreshFilters();$('janpadFilter').value=$('engineerFilter').value=$('clusterFilter').value='ALL';render()});$('printBtn').addEventListener('click',()=>window.print());document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');view=b.dataset.view;render()}));
$('csvBtn').addEventListener('click',()=>{if(!lastExport.length)return;const keys=Object.keys(lastExport[0]);const q=v=>'"'+String(v??'').replaceAll('"','""')+'"';const csv='\ufeff'+[keys.join(','),...lastExport.map(r=>keys.map(k=>q(r[k])).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`daily-report-${view}-${todayDate()}.csv`;a.click();URL.revokeObjectURL(a.href)});refreshFilters();render();updateAutoStatus();
// V6: Font size and Portrait/Landscape print controls
(function(){
  let fontScale=1;
  const root=document.documentElement;
  const minus=document.getElementById('fontMinusBtn');
  const plus=document.getElementById('fontPlusBtn');
  const orient=document.getElementById('printOrientation');
  const printBtn=document.getElementById('printBtn');
  function applyScale(){root.style.setProperty('--table-font-scale',fontScale.toFixed(2));}
  minus?.addEventListener('click',()=>{fontScale=Math.max(.75,+(fontScale-.10).toFixed(2));applyScale();});
  plus?.addEventListener('click',()=>{fontScale=Math.min(1.60,+(fontScale+.10).toFixed(2));applyScale();});
  function setPrintOrientation(){
    const mode=orient?.value==='portrait'?'portrait':'landscape';
    document.body.classList.toggle('print-portrait',mode==='portrait');
    document.body.classList.toggle('print-landscape',mode==='landscape');
    let st=document.getElementById('dynamicPrintPageStyle');
    if(!st){st=document.createElement('style');st.id='dynamicPrintPageStyle';document.head.appendChild(st);}
    st.textContent=`@media print{@page{size:A4 ${mode};margin:7mm}}`;
  }
  orient?.addEventListener('change',setPrintOrientation);
  if(printBtn){
    const cloned=printBtn.cloneNode(true);
    printBtn.parentNode.replaceChild(cloned,printBtn);
    cloned.addEventListener('click',()=>{setPrintOrientation();setTimeout(()=>window.print(),30);});
  }
  setPrintOrientation();applyScale();
})();
