(function(){
  const data=window.SHRAMIK_NIYOJAN;
  const apps=document.querySelector('#srdmApplications .srdm-app-grid');
  if(!apps||!data)return;
  const css=document.createElement('style');css.id='srdm-shramik-style';css.textContent=`
  #shramikNiyojanLauncher{--app-accent:#087f5b;--app-soft:#e9fbf4;--app-dark:#075d46;--app-shadow:rgba(8,127,91,.30);border:3px solid var(--app-accent)!important;background:linear-gradient(145deg,var(--app-soft),#fff 76%)!important}
  #shramikNiyojanLauncher .srdm-app-icon{background:#087f5b!important;color:#fff!important}
  #shramikNiyojanReport{display:none;margin:16px 0;background:#f4f8fb;border:1px solid #cddce7;border-radius:18px;padding:14px;box-shadow:0 12px 32px rgba(10,45,70,.12)}
  #shramikNiyojanReport.srdm-standalone-report-open{display:block!important}
  body.srdm-report-focus .shell>#shramikNiyojanReport{display:block!important}
  .sn-head{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;margin:4px 0 12px}.sn-head h2{margin:0;color:#064e3b;font-size:1.65rem}.sn-meta{font-size:.95rem;font-weight:800;color:#425466}.sn-badge{padding:8px 12px;border-radius:999px;background:#d7f7e9;color:#075d46;font-weight:900}
  .sn-tools{display:flex;gap:9px;flex-wrap:wrap;align-items:center;margin-bottom:12px}.sn-tools select,.sn-tools button{min-height:42px;padding:8px 13px;border:1.5px solid #087f5b;border-radius:10px;background:#fff;color:#123;font-size:15px;font-weight:850}.sn-tools button{background:#087f5b;color:#fff;cursor:pointer}
  .sn-kpis{display:grid;grid-template-columns:repeat(5,minmax(145px,1fr));gap:9px;margin-bottom:12px}.sn-kpi{background:#fff;border:1px solid #cfdee7;border-left:5px solid #087f5b;border-radius:12px;padding:10px}.sn-kpi small{display:block;color:#536575;font-size:13px;font-weight:800}.sn-kpi strong{display:block;color:#073b2d;font-size:1.3rem;margin-top:3px}
  .sn-wrap{overflow:auto;border:1px solid #b8cad6;border-radius:12px;background:#fff}.sn-table{width:100%;border-collapse:collapse;min-width:1220px;table-layout:fixed}.sn-table th{background:#075d46;color:#fff;padding:9px 6px;border:1px solid #2f806b;font-size:14px;line-height:1.2;position:sticky;top:0;z-index:1}.sn-table td{padding:8px 7px;border:1px solid #d8e3e9;font-size:15px;font-weight:750;text-align:right}.sn-table td:nth-child(-n+5){text-align:left}.sn-table tbody tr:nth-child(even){background:#f3fbf7}.sn-table .sn-district{background:#dff6eb;color:#064e3b;font-weight:950}.sn-table .sn-total{background:#c9eadc;color:#063d30;font-weight:950}.sn-table .sn-grand{background:#075d46;color:#fff;font-weight:950}.sn-pct{display:inline-block;min-width:68px;padding:5px 7px;border-radius:999px;text-align:center;background:#fff0c7;color:#7a4d00}.sn-pct.good{background:#d8f5e7;color:#09633f}.sn-pct.bad{background:#ffe0e0;color:#a31c1c}.sn-warning{margin:0 0 10px;padding:9px 11px;border:1px solid #e9a23b;border-radius:10px;background:#fff7e8;color:#7b4800;font-weight:750}.sn-source{font-size:13px;color:#586b78;text-align:right;margin-top:9px}
  @media(max-width:900px){.sn-kpis{grid-template-columns:repeat(2,minmax(135px,1fr))}.sn-head h2{font-size:1.35rem}.sn-table th{font-size:13px}.sn-table td{font-size:14px}}
  @media print{#shramikNiyojanReport{display:block!important;box-shadow:none;border:0}.sn-tools,.srdm-report-back{display:none!important}.sn-table th,.sn-table td{font-size:9px!important;padding:3px!important}.sn-kpis{grid-template-columns:repeat(5,1fr)}}`;
  document.head.appendChild(css);

  const card=document.createElement('button');card.type='button';card.id='shramikNiyojanLauncher';card.className='srdm-app-card report-module-card';card.innerHTML='<span class="srdm-app-icon">श</span><span class="srdm-app-copy"><strong>श्रमिक नियोजन</strong><span>अगस्त–सितम्बर मानव दिवस लक्ष्य एवं उपलब्धि</span></span><span class="module-indicator" aria-hidden="true"></span>';
  const mandays=apps.querySelector('[data-view="mandaysgen"]');
  if(mandays)mandays.insertAdjacentElement('afterend',card);else apps.appendChild(card);

  const section=document.createElement('section');section.id='shramikNiyojanReport';section.innerHTML=`<button type="button" class="srdm-report-back">← SRDM Applications पर वापस जाएँ</button><div class="sn-head"><div><h2>श्रमिक नियोजन — मानव दिवस लक्ष्य एवं उपलब्धि</h2><div class="sn-meta">FY 2025–26 अगस्त एवं सितम्बर में सृजित मानव दिवस के विरुद्ध FY 2026–27 उपलब्धि</div></div><span class="sn-badge" id="snDate">Live data</span></div><div class="sn-tools"><select id="snLevel"><option value="janpad">जिला एवं Janpad-wise</option><option value="engineer">Sub Engineer-wise</option></select><select id="snDistrict"><option value="ALL">SATNA + MAIHAR</option><option value="SATNA">SATNA</option><option value="MAIHAR">MAIHAR</option></select><select id="snJanpad"><option value="ALL">सभी Janpad</option></select><button type="button" id="snExcel">Excel डाउनलोड</button><button type="button" onclick="window.print()">प्रिंट / PDF</button></div><div id="snWarnings"></div><div class="sn-kpis" id="snKpis"></div><div class="sn-wrap"><table class="sn-table"><thead><tr><th>Rank</th><th>District</th><th>Janpad</th><th>Sub Engineer</th><th>Cluster(s)</th><th>FY 2025–26 अगस्त–सितम्बर में सृजित मानव दिवस</th><th>FY 2026–27 August</th><th>FY 2026–27 September</th><th>कुल उपलब्धि</th><th>Difference</th><th>शेष दिन</th><th>प्रतिदिन आवश्यकता</th><th>125% दैनिक लक्ष्य</th><th>उपलब्धि %</th></tr></thead><tbody id="snBody"></tbody></table></div><div class="sn-source">Official VB-G RAM G Employment Provided / Persondays report</div>`;
  document.getElementById('srdmApplications').insertAdjacentElement('afterend',section);
  const fmt=n=>Number(n||0).toLocaleString('en-IN'), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const level=document.getElementById('snLevel'),dist=document.getElementById('snDistrict'),jan=document.getElementById('snJanpad'),body=document.getElementById('snBody');let exportRows=[];
  function aggregate(rows,label,district){const t={district:district||'',janpad:label,engineer:'',cluster:'',target:0,augustAchievement:0,septemberAchievement:0,achievement:0,difference:0,remainingDays:Number(data.remainingSeptemberDays||0),dailyRequired:0,dailyTarget125:0,achievementPct:0};rows.forEach(r=>['target','augustAchievement','septemberAchievement','achievement'].forEach(k=>t[k]+=Number(r[k]||0)));t.difference=Math.max(0,t.target-t.achievement);t.dailyRequired=t.remainingDays?Math.ceil(t.difference/t.remainingDays):0;t.dailyTarget125=t.remainingDays?Math.ceil(t.difference/t.remainingDays*1.25):0;t.achievementPct=t.target?t.achievement*100/t.target:0;return t}
  function options(){const old=jan.value;const rows=(level.value==='engineer'?data.engineerRows:data.rows)||[];const vals=[...new Set(rows.filter(r=>dist.value==='ALL'||r.district===dist.value).map(r=>r.janpad))].sort();jan.innerHTML='<option value="ALL">सभी Janpad</option>'+vals.map(x=>`<option>${esc(x)}</option>`).join('');if(vals.includes(old))jan.value=old}
  function pctClass(v){return v>=100?'good':v<75?'bad':''}
  function row(r,rank,cls=''){return `<tr class="${cls}"><td>${rank||''}</td><td>${esc(r.district)}</td><td>${esc(r.janpad)}</td><td>${esc(r.engineer||'—')}</td><td>${esc(r.cluster||'—')}</td><td>${fmt(r.target)}</td><td>${fmt(r.augustAchievement)}</td><td>${fmt(r.septemberAchievement)}</td><td>${fmt(r.achievement)}</td><td>${fmt(r.difference)}</td><td>${fmt(r.remainingDays)}</td><td>${fmt(r.dailyRequired)}</td><td>${fmt(r.dailyTarget125)}</td><td><span class="sn-pct ${pctClass(r.achievementPct)}">${Number(r.achievementPct||0).toFixed(1)}%</span></td></tr>`}
  function draw(){let rows=(level.value==='engineer'?data.engineerRows:data.rows)||[];rows=rows.filter(r=>(dist.value==='ALL'||r.district===dist.value)&&(jan.value==='ALL'||r.janpad===jan.value));rows=rows.slice().sort((a,b)=>Number(b.achievementPct)-Number(a.achievementPct)||String(a.janpad).localeCompare(String(b.janpad))||String(a.engineer).localeCompare(String(b.engineer),'hi'));exportRows=rows;let h='';rows.forEach((r,i)=>h+=row(r,i+1));if(level.value==='janpad'&&jan.value==='ALL'){['SATNA','MAIHAR'].filter(d=>dist.value==='ALL'||dist.value===d).forEach(d=>{const q=rows.filter(r=>r.district===d);if(q.length)h+=row(aggregate(q,d+' जिला कुल',d),'','sn-district')});if(dist.value==='ALL'&&rows.length)h+=row(aggregate(rows,'SATNA + MAIHAR GRAND TOTAL',''),'','sn-grand')}else if(rows.length)h+=row(aggregate(rows,'TOTAL',dist.value==='ALL'?'':dist.value),'','sn-total');if(!rows.length)h='<tr><td colspan="14" style="text-align:center;padding:24px">Live data उपलब्ध नहीं है। One Click updater चलाएँ।</td></tr>';body.innerHTML=h;const total=aggregate(rows,'','');document.getElementById('snKpis').innerHTML=[['लक्ष्य',total.target],['उपलब्धि',total.achievement],['Difference',total.difference],['125% दैनिक लक्ष्य',total.dailyTarget125],['उपलब्धि %',total.achievementPct.toFixed(1)+'%']].map(x=>`<div class="sn-kpi"><small>${x[0]}</small><strong>${typeof x[1]==='number'?fmt(x[1]):x[1]}</strong></div>`).join('')}
  level.onchange=()=>{options();draw()};dist.onchange=()=>{options();draw()};jan.onchange=draw;options();draw();
  document.getElementById('snDate').textContent=data.officialDate?'As on '+data.officialDate:'Updater चलाना शेष';document.getElementById('snWarnings').innerHTML=(data.warnings||[]).map(x=>`<div class="sn-warning">${esc(x)}</div>`).join('');
  card.onclick=()=>{document.body.classList.add('srdm-report-focus');section.classList.add('srdm-standalone-report-open');section.scrollIntoView({behavior:'smooth',block:'start'})};section.querySelector('.srdm-report-back').onclick=()=>{section.classList.remove('srdm-standalone-report-open');document.body.classList.remove('srdm-report-focus');document.getElementById('srdmApplications').scrollIntoView({behavior:'smooth',block:'start'})};
  document.getElementById('snExcel').onclick=()=>{const head=['Rank','District','Janpad','Sub Engineer','Cluster','FY 2025-26 Aug+Sep Target','FY 2026-27 August','FY 2026-27 September','Achievement','Difference','Remaining Days','Daily Required','125% Daily Target','Achievement %'];const lines=[head,...exportRows.map((r,i)=>[i+1,r.district,r.janpad,r.engineer,r.cluster,r.target,r.augustAchievement,r.septemberAchievement,r.achievement,r.difference,r.remainingDays,r.dailyRequired,r.dailyTarget125,r.achievementPct])].map(a=>a.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+lines],{type:'text/csv'}));a.download='Shramik_Niyojan.csv';a.click()};
})();
