(function(){
  const data=window.SHRAMIK_NIYOJAN;
  const apps=document.querySelector('#srdmApplications .srdm-app-grid');
  if(!apps||!data)return;
  const css=document.createElement('style');css.id='srdm-shramik-style';css.textContent=`
  #shramikNiyojanLauncher{--app-accent:#087f5b;--app-soft:#e9fbf4;--app-dark:#075d46;--app-shadow:rgba(8,127,91,.30);border:3px solid var(--app-accent)!important;background:linear-gradient(145deg,var(--app-soft),#fff 76%)!important}
  #shramikNiyojanLauncher .srdm-app-icon{background:#087f5b!important;color:#fff!important}
  #shramikNiyojanReport{display:none;margin:16px 0;background:#f4f8fb;border:1px solid #cddce7;border-radius:18px;padding:14px;box-shadow:0 12px 32px rgba(10,45,70,.12)}
  #shramikNiyojanReport.srdm-standalone-report-open{display:block!important}
  .sn-head{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;margin:4px 0 12px}.sn-head h2{margin:0;color:#064e3b;font-size:1.65rem}.sn-meta{font-size:.95rem;font-weight:800;color:#425466}.sn-badge{padding:8px 12px;border-radius:999px;background:#d7f7e9;color:#075d46;font-weight:900}
  .sn-tools{display:flex;gap:9px;flex-wrap:wrap;align-items:center;margin-bottom:12px}.sn-tools select,.sn-tools button{min-height:42px;padding:8px 13px;border:1.5px solid #087f5b;border-radius:10px;background:#fff;color:#123;font-size:15px;font-weight:850}.sn-tools button{background:#087f5b;color:#fff;cursor:pointer}
  .sn-kpis{display:grid;grid-template-columns:repeat(5,minmax(145px,1fr));gap:9px;margin-bottom:12px}.sn-kpi{background:#fff;border:1px solid #cfdee7;border-left:5px solid #087f5b;border-radius:12px;padding:10px}.sn-kpi small{display:block;color:#536575;font-size:13px;font-weight:800}.sn-kpi strong{display:block;color:#073b2d;font-size:1.3rem;margin-top:3px}
  .sn-wrap{overflow:auto;border:3px solid #087f5b;border-radius:12px;background:#fff;box-shadow:0 5px 16px rgba(8,127,91,.12)}.sn-table{width:100%;border-collapse:collapse;min-width:1980px;table-layout:fixed;border:2px solid #075d46}.sn-table th{background:#075d46;color:#fff;padding:11px 7px;border:2px solid #58a792;font-size:20px;line-height:1.2;position:sticky;top:0;z-index:1;vertical-align:middle}.sn-table td{padding:10px 8px;border:2px solid #8ebcaf;font-size:20px;line-height:1.25;font-weight:750;text-align:right;background-clip:padding-box;vertical-align:middle}.sn-table td:nth-child(-n+5){text-align:left}.sn-table tbody tr:nth-child(even){background:#edf8f4}.sn-table tbody tr:hover{background:#dcf4eb}.sn-table .sn-district{font-weight:950;border-top:3px solid;border-bottom:3px solid}.sn-table .sn-district-maihar{background:#fff0c7!important;color:#704500!important;border-color:#d99000!important}.sn-table .sn-district-satna{background:#dcecff!important;color:#073d78!important;border-color:#2374bd!important}.sn-table .sn-total{background:#bfe7d6;color:#063d30;font-weight:950;border-top:3px solid #087f5b}.sn-table .sn-grand{background:#075d46;color:#fff;font-weight:950;border-top:3px solid #034a38}.sn-table .sn-grand td{border-color:#56a48f}.sn-shortage{color:#b42318;font-weight:950;background:#fff1f0!important}.sn-district-maihar .sn-shortage{background:#ffe3a3!important;color:#8a3d00}.sn-district-satna .sn-shortage{background:#bad8ff!important;color:#073d78}.sn-pct{display:inline-block;min-width:76px;padding:5px 7px;border-radius:999px;text-align:center;background:#fff0c7;color:#7a4d00}.sn-pct.good{background:#d8f5e7;color:#09633f}.sn-pct.bad{background:#ffe0e0;color:#a31c1c}.sn-warning{margin:0 0 10px;padding:9px 11px;border:1px solid #e9a23b;border-radius:10px;background:#fff7e8;color:#7b4800;font-weight:750}.sn-source{font-size:13px;color:#586b78;text-align:right;margin-top:9px}
  .sn-table th:nth-child(1),.sn-table td:nth-child(1){width:46px;padding-left:2px;padding-right:2px;text-align:center}
  .sn-table th:nth-child(2),.sn-table td:nth-child(2){width:68px;padding-left:3px;padding-right:3px}
  .sn-table th:nth-child(9),.sn-table td:nth-child(9){width:90px;padding-left:4px;padding-right:4px}
  .sn-table th:nth-child(10),.sn-table td:nth-child(10){width:82px;padding-left:4px;padding-right:4px}
  .sn-table th:nth-child(11),.sn-table td:nth-child(11){width:64px;padding-left:4px;padding-right:4px}
  .sn-table.sn-hide-engineer-cols th:nth-child(4),.sn-table.sn-hide-engineer-cols td:nth-child(4),.sn-table.sn-hide-engineer-cols th:nth-child(5),.sn-table.sn-hide-engineer-cols td:nth-child(5){display:none}
  .sn-table.sn-hide-engineer-cols{min-width:1180px}
  @media(max-width:900px){.sn-kpis{grid-template-columns:repeat(2,minmax(135px,1fr))}.sn-head h2{font-size:1.35rem}.sn-table th,.sn-table td{font-size:20px}}
  @media print{
    @page{size:A4 landscape!important;margin:4mm!important}
    html,body{width:100%!important;height:auto!important;margin:0!important;padding:0!important;-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important}
    body{overflow:visible!important}.shell{width:100%!important;max-width:none!important;margin:0!important;padding:0!important}
    #shramikNiyojanReport{display:block!important;width:100%!important;margin:0!important;padding:0!important;box-shadow:none!important;border:0!important;background:#fff!important}
    #shramikNiyojanReport .sn-tools,#shramikNiyojanReport .srdm-report-back,#shramikNiyojanReport .sn-source{display:none!important}
    #shramikNiyojanReport .sn-head{margin:0 0 3mm!important}#shramikNiyojanReport .sn-head h2{font-size:16pt!important}#shramikNiyojanReport .sn-meta,#shramikNiyojanReport .sn-badge{font-size:9pt!important}
    #shramikNiyojanReport .sn-kpis{display:grid!important;grid-template-columns:repeat(5,1fr)!important;gap:2mm!important;margin-bottom:3mm!important}#shramikNiyojanReport .sn-kpi{padding:2mm!important;border:1.5px solid #087f5b!important}#shramikNiyojanReport .sn-kpi small{font-size:8pt!important}#shramikNiyojanReport .sn-kpi strong{font-size:11pt!important}
    #shramikNiyojanReport .sn-wrap{width:100%!important;overflow:visible!important;border:2px solid #075d46!important;border-radius:0!important;box-shadow:none!important}
    #shramikNiyojanReport .sn-table{width:100%!important;min-width:0!important;table-layout:fixed!important;border-collapse:collapse!important;border:2px solid #075d46!important}
    #shramikNiyojanReport .sn-table thead{display:table-header-group!important}#shramikNiyojanReport .sn-table tr{break-inside:avoid!important;page-break-inside:avoid!important}
    #shramikNiyojanReport .sn-table th,#shramikNiyojanReport .sn-table td{font-size:8.5pt!important;line-height:1.08!important;padding:1.4mm .7mm!important;border:1.5px solid #427f70!important;white-space:normal!important;overflow-wrap:anywhere!important;word-break:break-word!important}
    #shramikNiyojanReport .sn-table th:nth-child(1),#shramikNiyojanReport .sn-table td:nth-child(1){width:3.5%!important}
    #shramikNiyojanReport .sn-table th:nth-child(2),#shramikNiyojanReport .sn-table td:nth-child(2){width:5%!important}
    #shramikNiyojanReport .sn-table th:nth-child(3),#shramikNiyojanReport .sn-table td:nth-child(3){width:7.5%!important}
    #shramikNiyojanReport .sn-table th:nth-child(6),#shramikNiyojanReport .sn-table td:nth-child(6){width:9%!important}
    #shramikNiyojanReport .sn-table.sn-hide-engineer-cols th:nth-child(4),#shramikNiyojanReport .sn-table.sn-hide-engineer-cols td:nth-child(4),#shramikNiyojanReport .sn-table.sn-hide-engineer-cols th:nth-child(5),#shramikNiyojanReport .sn-table.sn-hide-engineer-cols td:nth-child(5){display:none!important}
    #shramikNiyojanReport .sn-pct{min-width:0!important;padding:.8mm!important;border:1px solid currentColor!important}
  }`;
  document.head.appendChild(css);

  const card=document.createElement('button');card.type='button';card.id='shramikNiyojanLauncher';card.className='srdm-app-card report-module-card';card.innerHTML='<span class="srdm-app-icon">श</span><span class="srdm-app-copy"><strong>श्रमिक नियोजन</strong><span>अगस्त–सितम्बर मानव दिवस लक्ष्य एवं उपलब्धि</span></span><span class="module-indicator" aria-hidden="true"></span>';
  const mandays=apps.querySelector('[data-view="mandaysgen"]');
  if(mandays)mandays.insertAdjacentElement('afterend',card);else apps.appendChild(card);

  const section=document.createElement('section');section.id='shramikNiyojanReport';section.innerHTML=`<button type="button" class="srdm-report-back">← एसआरडीएम अनुप्रयोग पर वापस जाएँ</button><div class="sn-head"><div><h2>श्रमिक नियोजन — मानव दिवस लक्ष्य एवं उपलब्धि</h2><div class="sn-meta">वित्तीय वर्ष 2025–26 के अगस्त एवं सितम्बर में सृजित मानव दिवस के विरुद्ध वित्तीय वर्ष 2026–27 की उपलब्धि</div></div><span class="sn-badge" id="snDate">लाइव आँकड़े</span></div><div class="sn-tools"><select id="snLevel"><option value="janpad">जिला एवं जनपदवार</option><option value="engineer">उपयंत्री एवं क्लस्टरवार</option></select><select id="snDistrict"><option value="ALL">सतना + मैहर</option><option value="SATNA">सतना</option><option value="MAIHAR">मैहर</option></select><select id="snJanpad"><option value="ALL">सभी जनपद</option></select><button type="button" id="snExcel">एक्सेल डाउनलोड</button><button type="button" onclick="window.print()">प्रिंट / पीडीएफ</button></div><div id="snWarnings"></div><div class="sn-kpis" id="snKpis"></div><div class="sn-wrap"><table class="sn-table"><thead><tr><th>क्रमांक</th><th>जिला</th><th>जनपद</th><th>उपयंत्री</th><th>क्लस्टर</th><th>वित्तीय वर्ष 2025–26 अगस्त–सितम्बर में सृजित मानव दिवस</th><th>वित्तीय वर्ष 2026–27 अगस्त</th><th>वित्तीय वर्ष 2026–27 सितम्बर</th><th>कुल उपलब्धि</th><th>अंतर</th><th>शेष दिन</th><th>प्रतिदिन श्रमिक का लक्ष्य</th><th>आज संलग्न श्रमिक</th><th>उपलब्धि %</th><th>लक्ष्य अनुसार श्रमिक नियोजन में कमी</th><th>कुल प्रगतिरत कार्य</th><th>आज कार्यों पर जारी मस्टर रोल</th><th>मस्टर रोल जारी %</th></tr></thead><tbody id="snBody"></tbody></table></div><div class="sn-source">आधिकारिक वीबी-जी राम जी रोजगार प्रदाय / मानव दिवस रिपोर्ट</div>`;
  document.getElementById('srdmApplications').insertAdjacentElement('afterend',section);
  const fmt=n=>Number(n||0).toLocaleString('en-IN'), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const level=document.getElementById('snLevel'),dist=document.getElementById('snDistrict'),jan=document.getElementById('snJanpad'),body=document.getElementById('snBody'),auto=window.AUTO_REPORT||{};let exportRows=[];
  const nrm=v=>String(v||'').replace(/\s+/g,' ').trim().toUpperCase();
  const janpadHindi={AMARPATAN:'अमरपाटन',MAIHAR:'मैहर',MAJHGAWAN:'मझगवां',NAGOD:'नागौद',RAMNAGAR:'रामनगर','RAMPUR BAGHELAN':'रामपुर बघेलान',SATNA:'सतना',UNCHAHARA:'उचेहरा'};
  const districtHindi=v=>nrm(v)==='MAIHAR'?'मैहर':nrm(v)==='SATNA'?'सतना':v;
  const janpadName=v=>janpadHindi[nrm(v)]||v;
  function liveMetrics(){const m=new Map();for(const r of auto.rows||[]){const j=nrm(r.janpad),e=String(r.engineer||'Unmapped').trim(),c=String(r.cluster||'Unmapped').trim(),k=[j,e,c].join('¦');if(!m.has(k))m.set(k,{janpad:j,engineer:e,cluster:c,gp:0,labour:0,ongoing:0,mrIssued:0});const z=m.get(k);z.gp+=Number(r.gps||1);z.labour+=Number(r.labour||0);z.ongoing+=Number(r.ongoing||0);z.mrIssued+=Number(r.worksMR||0)}return m}
  const metrics=liveMetrics();
  function apportion(total,list,weight){const weights=list.map(x=>Math.max(0,Number(x[weight]||0))),sum=weights.reduce((a,b)=>a+b,0),baseWeights=sum?weights:list.map(x=>Math.max(1,Number(x.gp||1))),den=baseWeights.reduce((a,b)=>a+b,0)||1,raw=baseWeights.map(x=>Number(total||0)*x/den),out=raw.map(Math.floor);let left=Math.round(Number(total||0))-out.reduce((a,b)=>a+b,0);raw.map((v,i)=>({i,f:v-out[i]})).sort((a,b)=>b.f-a.f).slice(0,left).forEach(x=>out[x.i]++);return out}
  function buildEngineerRows(){if((data.engineerRows||[]).length){return data.engineerRows.map(r=>{const q=metrics.get([nrm(r.janpad),String(r.engineer||'').trim(),String(r.cluster||'').trim()].join('¦'))||{};return {...r,todayLabour:Number(q.labour||0),ongoing:Number(q.ongoing||0),mrIssued:Number(q.mrIssued||0)}})}const out=[];for(const parent of data.rows||[]){const members=[...metrics.values()].filter(x=>x.janpad===nrm(parent.janpad));if(!members.length)continue;const targets=apportion(parent.target,members,'gp'),aug=apportion(parent.augustAchievement,members,'labour'),sep=apportion(parent.septemberAchievement,members,'labour');members.forEach((m,i)=>{const target=targets[i],achievement=aug[i]+sep[i],difference=Math.max(0,target-achievement),days=Number(parent.remainingDays||data.remainingSeptemberDays||0);out.push({level:'engineer',district:parent.district,janpad:parent.janpad,engineer:m.engineer,cluster:m.cluster,target,augustAchievement:aug[i],septemberAchievement:sep[i],achievement,difference,remainingDays:days,dailyRequired:days?Math.ceil(difference/days):0,dailyTarget125:days?Math.ceil(difference/days*1.25):0,achievementPct:target?achievement*100/target:0,todayLabour:m.labour,ongoing:m.ongoing,mrIssued:m.mrIssued})})}return out}
  const engineerRows=buildEngineerRows();
  const officialMap=new Map((auto.official||[]).map(r=>[nrm(r.janpad),r]));
  const janpadRows=(data.rows||[]).map(r=>{const o=officialMap.get(nrm(r.janpad))||{},fallback=[...metrics.values()].filter(x=>x.janpad===nrm(r.janpad));return {...r,todayLabour:Number(o.labourAll??fallback.reduce((a,x)=>a+x.labour,0)),ongoing:Number(o.ongoingAll??fallback.reduce((a,x)=>a+x.ongoing,0)),mrIssued:Number(o.mrAll??fallback.reduce((a,x)=>a+x.mrIssued,0))}});
  function aggregate(rows,label,district){const t={district:district||'',janpad:label,engineer:'',cluster:'',target:0,augustAchievement:0,septemberAchievement:0,achievement:0,difference:0,remainingDays:Number(data.remainingSeptemberDays||0),dailyRequired:0,dailyTarget125:0,todayLabour:0,achievementPct:0,ongoing:0,mrIssued:0};rows.forEach(r=>['target','augustAchievement','septemberAchievement','achievement','todayLabour','ongoing','mrIssued'].forEach(k=>t[k]+=Number(r[k]||0)));t.difference=Math.max(0,t.target-t.achievement);t.dailyRequired=t.remainingDays?Math.ceil(t.difference/t.remainingDays):0;t.dailyTarget125=t.remainingDays?Math.ceil(t.difference/t.remainingDays*1.25):0;t.achievementPct=t.target?t.achievement*100/t.target:0;return t}
  function options(){const old=jan.value;const rows=level.value==='engineer'?engineerRows:janpadRows;const vals=[...new Set(rows.filter(r=>dist.value==='ALL'||r.district===dist.value).map(r=>r.janpad))].sort();jan.innerHTML='<option value="ALL">सभी जनपद</option>'+vals.map(x=>`<option value="${esc(x)}">${esc(janpadName(x))}</option>`).join('');if(vals.includes(old))jan.value=old}
  function pctClass(v){return v>=100?'good':v<75?'bad':''}
  function row(r,rank,cls=''){const mrPct=Number(r.ongoing||0)?Number(r.mrIssued||0)*100/Number(r.ongoing):0,shortage=Math.max(0,Number(r.dailyTarget125||0)-Number(r.todayLabour||0));return `<tr class="${cls}"><td>${rank||''}</td><td>${esc(districtHindi(r.district))}</td><td>${esc(janpadName(r.janpad))}</td><td>${esc(r.engineer||'—')}</td><td>${esc(r.cluster||'—')}</td><td>${fmt(r.target)}</td><td>${fmt(r.augustAchievement)}</td><td>${fmt(r.septemberAchievement)}</td><td>${fmt(r.achievement)}</td><td>${fmt(r.difference)}</td><td>${fmt(r.remainingDays)}</td><td>${fmt(r.dailyTarget125)}</td><td>${fmt(r.todayLabour)}</td><td><span class="sn-pct ${pctClass(r.achievementPct)}">${Number(r.achievementPct||0).toFixed(1)}%</span></td><td class="sn-shortage">${fmt(shortage)}</td><td>${fmt(r.ongoing)}</td><td>${fmt(r.mrIssued)}</td><td>${mrPct.toFixed(1)}%</td></tr>`}
  function draw(){
    section.querySelector('.sn-table').classList.toggle('sn-hide-engineer-cols',level.value==='janpad');
    let rows=level.value==='engineer'?engineerRows:janpadRows;
    rows=rows.filter(r=>(dist.value==='ALL'||r.district===dist.value)&&(jan.value==='ALL'||r.janpad===jan.value));
    const order=['AMARPATAN','MAIHAR','RAMNAGAR','MAJHGAWAN','NAGOD','RAMPUR BAGHELAN','SATNA','UNCHAHARA'];
    rows=rows.slice().sort((a,b)=>order.indexOf(nrm(a.janpad))-order.indexOf(nrm(b.janpad))||String(a.engineer).localeCompare(String(b.engineer),'hi'));
    exportRows=rows;let h='',serial=1;
    if(level.value==='janpad'&&jan.value==='ALL'){
      ['MAIHAR','SATNA'].filter(d=>dist.value==='ALL'||dist.value===d).forEach(d=>{
        const q=rows.filter(r=>r.district===d);
        q.forEach(r=>h+=row(r,serial++));
        if(q.length)h+=row(aggregate(q,d==='SATNA'?'सतना जिला कुल':'मैहर जिला कुल',d),'',`sn-district sn-district-${d.toLowerCase()}`);
      });
      if(dist.value==='ALL'&&rows.length)h+=row(aggregate(rows,'सतना + मैहर महायोग',''),'','sn-grand');
    }else{
      rows.forEach(r=>h+=row(r,serial++));
      if(rows.length)h+=row(aggregate(rows,'कुल',dist.value==='ALL'?'':dist.value),'','sn-total');
    }
    if(!rows.length)h='<tr><td colspan="18" style="text-align:center;padding:24px">लाइव आँकड़े उपलब्ध नहीं हैं। वन क्लिक अपडेटर चलाएँ।</td></tr>';
    body.innerHTML=h;const total=aggregate(rows,'','');
    document.getElementById('snKpis').innerHTML=[['लक्ष्य',total.target],['उपलब्धि',total.achievement],['अंतर',total.difference],['दैनिक लक्ष्य',total.dailyTarget125],['उपलब्धि %',total.achievementPct.toFixed(1)+'%']].map(x=>`<div class="sn-kpi"><small>${x[0]}</small><strong>${typeof x[1]==='number'?fmt(x[1]):x[1]}</strong></div>`).join('')
  }
  level.onchange=()=>{options();draw()};dist.onchange=()=>{options();draw()};jan.onchange=draw;options();draw();
  document.getElementById('snDate').textContent=data.officialDate?'दिनांक '+data.officialDate:'अपडेटर चलाना शेष';document.getElementById('snWarnings').innerHTML=(data.warnings||[]).map(x=>`<div class="sn-warning">${esc(x)}</div>`).join('');
  card.onclick=()=>{document.querySelectorAll('#yuktdharaMonitoring,#musterEmbMonitoring').forEach(x=>x.classList.remove('srdm-standalone-report-open'));document.body.classList.add('srdm-report-focus');section.classList.add('srdm-standalone-report-open');section.scrollIntoView({behavior:'smooth',block:'start'})};section.querySelector('.srdm-report-back').onclick=()=>{section.classList.remove('srdm-standalone-report-open');document.body.classList.remove('srdm-report-focus');document.getElementById('srdmApplications').scrollIntoView({behavior:'smooth',block:'start'})};
  document.addEventListener('click',event=>{if(event.target.closest('#yuktdharaLauncher,#musterEmbLauncher'))section.classList.remove('srdm-standalone-report-open')},true);
  document.getElementById('snExcel').onclick=()=>{const head=['क्रमांक','जिला','जनपद','उपयंत्री','क्लस्टर','वित्तीय वर्ष 2025-26 अगस्त-सितम्बर मानव दिवस','वित्तीय वर्ष 2026-27 अगस्त','वित्तीय वर्ष 2026-27 सितम्बर','कुल उपलब्धि','अंतर','शेष दिन','प्रतिदिन श्रमिक का लक्ष्य','आज संलग्न श्रमिक','उपलब्धि %','लक्ष्य अनुसार श्रमिक नियोजन में कमी','कुल प्रगतिरत कार्य','आज कार्यों पर जारी मस्टर रोल','मस्टर रोल जारी %'];const lines=[head,...exportRows.map((r,i)=>[i+1,r.district,r.janpad,r.engineer,r.cluster,r.target,r.augustAchievement,r.septemberAchievement,r.achievement,r.difference,r.remainingDays,r.dailyTarget125,r.todayLabour,r.achievementPct,Math.max(0,Number(r.dailyTarget125||0)-Number(r.todayLabour||0)),r.ongoing,r.mrIssued,Number(r.ongoing||0)?Number(r.mrIssued||0)*100/Number(r.ongoing):0])].map(a=>a.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+lines],{type:'text/csv'}));a.download='Shramik_Niyojan.csv';a.click()};
})();
